/*
 * unicode.h
 * This file is part of logics
 *
 * Copyright (C) 2014 - César González <ceguel@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the GNU
 * Lesser General Public License for more details.
 */

#ifndef UNICODE_H_
#define UNICODE_H_

#include <glibmm/unicode.h>
#include <glibmm/ustring.h>

namespace Unicode
{

const gunichar
	// Basic Latin (ASCII)
	EXCLAMATION_MARK                             = (gunichar) '!',
	QUOTATION_MARK                               = (gunichar) '\"',
	NUMBER_SIGN                                  = (gunichar) '#',
	DOLLAR_SIGN                                  = (gunichar) '$',
	PERCENT_SIGN                                 = (gunichar) '%',
	AMPERSAND                                    = (gunichar) '&',
	APOSTROPHE                                   = (gunichar) '\'',
	LEFT_PARENTHESIS                             = (gunichar) '(',
	RIGHT_PARENTHESIS                            = (gunichar) ')',
	ASTERISK                                     = (gunichar) '*',
	PLUS_SIGN                                    = (gunichar) '+',
	COMMA                                        = (gunichar) ',',
	HYPHEN_MINUS                                 = (gunichar) '-',
	FULL_STOP                                    = (gunichar) '.',
	SOLIDUS                                      = (gunichar) '/',
	COLON                                        = (gunichar) ':',
	SEMICOLON                                    = (gunichar) ';',
	LESS_THAN_SIGN                               = (gunichar) '<',
	EQUALS_SIGN                                  = (gunichar) '=',
	GREATER_THAN_SIGN                            = (gunichar) '>',
	QUESTION_MARK                                = (gunichar) '?',
	COMMERCIAL_AT                                = (gunichar) '@',
	LEFT_SQUARE_BRACKET                          = (gunichar) '[',
	REVERSE_SOLIDUS                              = (gunichar) '\\',
	RIGHT_SQUARE_BRACKET                         = (gunichar) ']',
	CIRCUMFLEX_ACCENT                            = (gunichar) '^',
	LOW_LINE                                     = (gunichar) '_',
	GRAVE_ACCENT                                 = (gunichar) '`',
	LEFT_CURLY_BRACKET                           = (gunichar) '{',
	VERTICAL_LINE                                = (gunichar) '|',
	RIGHT_CURLY_BRACKET                          = (gunichar) '}',
	TILDE                                        = (gunichar) '~',

	// Latin-1 Supplement
	NOT_SIGN                                     = 0x00AC,
	DEGREE_SIGN                                  = 0x00B0,
	PLUS_MINUS_SIGN                              = 0x00B1,
	SUPERSCRIPT_TWO                              = 0x00B2,
	SUPERSCRIPT_THREE                            = 0x00B3,
	MICRO_SIGN                                   = 0x00B5,
	MIDDLE_DOT                                   = 0x00B7,
	SUPERSCRIPT_ONE                              = 0x00B9,
	VULGAR_FRACTION_ONE_QUARTER                  = 0x00BC,
	VULGAR_FRACTION_ONE_HALF                     = 0x00BD,
	VULGAR_FRACTION_THREE_QUARTERS               = 0x00BE,
	MULTIPLICATION_SIGN                          = 0x00D7,
	DIVISION_SIGN                                = 0x00F7,

	// Greek
	GREEK_CAPITAL_LETTER_ALPHA                   = 0x0391,
	GREEK_CAPITAL_LETTER_BETA                    = 0x0392,
	GREEK_CAPITAL_LETTER_GAMMA                   = 0x0393,
	GREEK_CAPITAL_LETTER_DELTA                   = 0x0394,
	GREEK_CAPITAL_LETTER_EPSILON                 = 0x0395,
	GREEK_CAPITAL_LETTER_ZETA                    = 0x0396,
	GREEK_CAPITAL_LETTER_ETA                     = 0x0397,
	GREEK_CAPITAL_LETTER_THETA                   = 0x0398,
	GREEK_CAPITAL_LETTER_IOTA                    = 0x0399,
	GREEK_CAPITAL_LETTER_KAPPA                   = 0x034A,
	GREEK_CAPITAL_LETTER_LAMDA                   = 0x039B,
	GREEK_CAPITAL_LETTER_MU                      = 0x039C,
	GREEK_CAPITAL_LETTER_NU                      = 0x039D,
	GREEK_CAPITAL_LETTER_XI                      = 0x039E,
	GREEK_CAPITAL_LETTER_OMICRON                 = 0x039F,
	GREEK_CAPITAL_LETTER_PI                      = 0x03A0,
	GREEK_CAPITAL_LETTER_RHO                     = 0x03A1,
	GREEK_CAPITAL_LETTER_SIGMA                   = 0x03A3,
	GREEK_CAPITAL_LETTER_TAU                     = 0x03A4,
	GREEK_CAPITAL_LETTER_UPSILON                 = 0x03A5,
	GREEK_CAPITAL_LETTER_PHI                     = 0x03A6,
	GREEK_CAPITAL_LETTER_CHI                     = 0x03A7,
	GREEK_CAPITAL_LETTER_PSI                     = 0x03A8,
	GREEK_CAPITAL_LETTER_OMEGA                   = 0x03A9,
	GREEK_SMALL_LETTER_ALPHA                     = 0x03B1,
	GREEK_SMALL_LETTER_BETA                      = 0x03B2,
	GREEK_SMALL_LETTER_GAMMA                     = 0x03B3,
	GREEK_SMALL_LETTER_DELTA                     = 0x03B4,
	GREEK_SMALL_LETTER_EPSILON                   = 0x03B5,
	GREEK_SMALL_LETTER_ZETA                      = 0x03B6,
	GREEK_SMALL_LETTER_ETA                       = 0x03B7,
	GREEK_SMALL_LETTER_THETA                     = 0x03B8,
	GREEK_SMALL_LETTER_IOTA                      = 0x03B9,
	GREEK_SMALL_LETTER_KAPPA                     = 0x03BA,
	GREEK_SMALL_LETTER_LAMDA                     = 0x03BB,
	GREEK_SMALL_LETTER_MU                        = 0x03BC,
	GREEK_SMALL_LETTER_NU                        = 0x03BD,
	GREEK_SMALL_LETTER_XI                        = 0x03BE,
	GREEK_SMALL_LETTER_OMICRON                   = 0x03BF,
	GREEK_SMALL_LETTER_PI                        = 0x03C0,
	GREEK_SMALL_LETTER_RHO                       = 0x03C1,
	GREEK_SMALL_LETTER_FINAL_SIGMA               = 0x03C2,
	GREEK_SMALL_LETTER_SIGMA                     = 0x03C3,
	GREEK_SMALL_LETTER_TAU                       = 0x03C4,
	GREEK_SMALL_LETTER_UPSILON                   = 0x03C5,
	GREEK_SMALL_LETTER_PHI                       = 0x03C6,
	GREEK_SMALL_LETTER_CHI                       = 0x03C7,
	GREEK_SMALL_LETTER_PSI                       = 0x03C8,
	GREEK_SMALL_LETTER_OMEGA                     = 0x03C9,
	GREEK_BETA_SYMBOL                            = 0x03D0,
	GREEK_THETA_SYMBOL                           = 0x03D1,
	SCRIPT_THETA                                 = GREEK_THETA_SYMBOL,
	GREEK_UPSILON_WITH_HOOK_SYMBOL               = 0x03D2,
	GREEK_PHI_SYMBOL                             = 0x03D5,
	GREEK_PI_SYMBOL                              = 0x03D6,
	OMEGA_PI                                     = GREEK_PI_SYMBOL,
	GREEK_KAI_SYMBOL                             = 0x03D7,
	GREEK_LETTER_ARCHAIC_KOPPA                   = 0x03D8,
	GREEK_SMALL_LETTER_ARCHAIC_KOPPA             = 0x03D9,
	GREEK_LETTER_STIGMA                          = 0x03DA,
	GREEK_SMALL_LETTER_STIGMA                    = 0x03DB,
	GREEK_LETTER_DIGAMMA                         = 0x03DC,
	GREEK_SMALL_LETTER_DIGAMMA                   = 0x03DD,
	GREEK_LETTER_KOPPA                           = 0x03DE,
	GREEK_SMALL_LETTER_KOPPA                     = 0x03DF,
	GREEK_LETTER_SAMPI                           = 0x03E0,
	GREEK_SMALL_LETTER_SAMPI                     = 0x03E1,
	GREEK_KAPPA_SYMBOL                           = 0x03F0,
	SCRIPT_KAPPA                                 = GREEK_KAPPA_SYMBOL,
	GREEK_RHO_SYMBOL                             = 0x03F1,
	GREEK_LUNATE_SIGMA_SYMBOL                    = 0x03F2,
	GREEK_LETTER_YOT                             = 0x03F3,
	GREEK_CAPITAL_THETA_SYMBOL                   = 0x03F4,
	GREEK_LUNATE_EPSILON_SYMBOL                  = 0x03F5,
	GREEK_EPSILON_SYMBOL                         = GREEK_LUNATE_EPSILON_SYMBOL,
	STRAIGHT_EPSILON                             = GREEK_LUNATE_EPSILON_SYMBOL,
	GREEK_REVERSED_LUNATE_EPSILON_SYMBOL         = 0x03F6,
	REVERSED_STRAIGHT_EPSILON                    = GREEK_REVERSED_LUNATE_EPSILON_SYMBOL,
	GREEK_CAPITAL_LETTER_SHO                     = 0x03F7,
	GREEK_SMALL_LETTER_SHO                       = 0x03F8,
	GREEK_CAPITAL_LUNATE_SIGMA_SYMBOL            = 0x03F9,
	GREEK_CAPITAL_LETTER_SAN                     = 0x03FA,
	GREEK_SMALL_LETTER_SAN                       = 0x03FB,
	GREEK_RHO_WITH_STROKE_SYMBOL                 = 0x03FC,
	GREEK_CAPITAL_REVERSED_LUNATE_SIGMA_SYMBOL   = 0x03FD,
	ANTISIGMA                                    = GREEK_CAPITAL_REVERSED_LUNATE_SIGMA_SYMBOL,
	GREEK_CAPITAL_DOTTED_LUNATE_SIGMA_SYMBOL     = 0x03FE,
	SIGMA_PERIESTIGMENON                         = GREEK_CAPITAL_DOTTED_LUNATE_SIGMA_SYMBOL,
	GREEK_CAPITAL_REVERSED_DOTTED_LUNATE_SIGMA_SYMBOL
	                                             = 0x03FF,
	ANTISIGMA_PERIESTIGMENON                     = GREEK_CAPITAL_REVERSED_DOTTED_LUNATE_SIGMA_SYMBOL,

	// Hebrew
	HEBREW_LETTER_ALEF                           = 0x05D0,
	HEBREW_LETTER_BET                            = 0x05D1,
	HEBREW_LETTER_GIMEOL                         = 0x05D2,
	HEBREW_LETTER_DALET                          = 0x05D3,
	HEBREW_LETTER_HE                             = 0x05D4,
	HEBREW_LETTER_VAV                            = 0x05D5,
	HEBREW_LETTER_ZAYIN                          = 0x05D6,
	HEBREW_LETTER_HET                            = 0x05D7,
	HEBREW_LETTER_TET                            = 0x05D8,
	HEBREW_LETTER_YOD                            = 0x05D9,
	HEBREW_LETTER_FINAL_KAF                      = 0x05DA,
	HEBREW_LETTER_KAF                            = 0x05DB,
	HEBREW_LETTER_LAMED                          = 0x05DC,
	HEBREW_LETTER_FINAL_MEM                      = 0x05DD,
	HEBREW_LETTER_MEM                            = 0x05DE,
	HEBREW_LETTER_FINAL_NUN                      = 0x05DF,
	HEBREW_LETTER_NUN                            = 0x05E0,
	HEBREW_LETTER_SAMEKH                         = 0x05E1,
	HEBREW_LETTER_AYIN                           = 0x05E2,
	HEBREW_LETTER_FINAL_PE                       = 0x05E3,
	HEBREW_LETTER_PE                             = 0x05E4,
	HEBREW_LETTER_FINAL_TSADI                    = 0x05E5,
	HEBREW_LETTER_TSADI                          = 0x05E6,
	HEBREW_LETTER_QOF                            = 0x05E7,
	HEBREW_LETTER_RESH                           = 0x05E8,
	HEBREW_LETTER_SHIN                           = 0x05E9,
	HEBREW_LETTER_TAV                            = 0x05EA,

	// Superscripts and Subscripts 2080-209F

	// Letterlike Symbols
	DOUBLE_STRUCK_CAPITAL_C                      = 0x2102,
	SET_COMPLEX_NUMBERS                          = DOUBLE_STRUCK_CAPITAL_C,
	EULER_CONSTANT                               = 0x2107,
	SCRIPT_SMALL_G                               = 0x210A,
	REAL_NUMBER_SYMBOL                           = SCRIPT_SMALL_G,
	SCRIPT_CAPITAL_H                             = 0x210B,
	HAMILTONIAN_OPERATOR                         = SCRIPT_CAPITAL_H,
	BLACK_LETTER_CAPITAL_H                       = 0x210C,
	HILBERT_SPACE                                = BLACK_LETTER_CAPITAL_H,
	DOUBLE_STRUCK_CAPITAL_H                      = 0x210D,
	PLANK_CONSTANT                               = 0x210E,
	PLANK_CONSTANT_OVER_TWO_PI                   = 0x210F,
	SCRIPT_CAPITAL_I                             = 0x2110,
	BLACK_LETTER_CAPITAL_I                       = 0x2111,
	IMAGINARY_PART                               = BLACK_LETTER_CAPITAL_I,
	SCRIPT_CAPITAL_L                             = 0x2112,
	LAPLACE_TRANSFORM                            = SCRIPT_CAPITAL_L,
	SCRIPT_SMALL_L                               = 0x2113,
	MATHEMATICAL_SYMBOL_ELL                      = 0x2113,
	DOUBLE_STRUCK_CAPITAL_N                      = 0x2115,
	SET_NATURAL_NUMBERS                          = DOUBLE_STRUCK_CAPITAL_N,
	DOUBLE_STRUCK_CAPITAL_P                      = 0x2119,
	DOUBLE_STRUCK_CAPITAL_Q                      = 0x211A,
	SET_RATIONAL_NUMBERS                         = DOUBLE_STRUCK_CAPITAL_Q,
	SCRIPT_CAPITAL_R                             = 0x211B,
	RIEMANN_INTEGRAL                             = SCRIPT_CAPITAL_R,
	BLACK_LETTER_CAPITAL_R                       = 0x211C,
	REAL_PART                                    = BLACK_LETTER_CAPITAL_R,
	DOUBLE_STRUCK_CAPITAL_R                      = 0x211D,
	SET_REAL_NUMBERS                             = DOUBLE_STRUCK_CAPITAL_R,
	DOUBLE_STRUCK_CAPITAL_Z                      = 0x2124,
	SET_INTEGERS                                 = DOUBLE_STRUCK_CAPITAL_Z,
	BLACK_LETTER_CAPITAL_Z                       = 0x2128,
	TURNED_GREEK_SMALL_LETTER_IOTA               = 0x2129,
	UNIQUE_ELEMENT_FULFILLING_A_DESCRIPTION      = TURNED_GREEK_SMALL_LETTER_IOTA,
	SCRIPT_CAPITAL_B                             = 0x212C,
	BERNOULLI_FUNCTION                           = SCRIPT_CAPITAL_B,
	BLACK_LETTER_CAPITAL_C                       = 0x212D,
	SCRIPT_SMALL_E                               = 0x212F,
	SCRIPT_CAPITAL_E                             = 0x2130,
	SCRIPT_CAPITAL_F                             = 0x2131,
	FOURIER_TRANSFORM                            = SCRIPT_CAPITAL_F,
	SCRIPT_CAPITAL_M                             = 0x2133,
	SCRIPT_SMALL_O                               = 0x2134,
	ALEF_SYMBOL                                  = 0x2135,
	FIRST_TRANSFINITE_CARDINAL                   = ALEF_SYMBOL,
	COUNTABLE                                    = ALEF_SYMBOL,
	BET_SYMBOL                                   = 0x2136,
	SECOND_TRANSFINITE_CARDINAL                  = BET_SYMBOL,
	CONTINUUM                                    = BET_SYMBOL,
	GIMEL_SYMBOL                                 = 0x2137,
	THIRD_TRANSFINITE_CARDINAL                   = GIMEL_SYMBOL,
	FUNCTIONS_OF_A_REAL_VARIABLE                 = GIMEL_SYMBOL,
	DALET_SYMBOL                                 = 0x2138,
	FOURTH_TRANSFINITE_CARDINAL                  = DALET_SYMBOL,
	TURNED_AMPERSAND                             = 0x214B,

	// Arrows
	LEFTWARDS_ARROW                              = 0x2190,
	UPWARDS_ARROW                                = 0x2191,
	RIGHTWARDS_ARROW                             = 0x2192,
	DOWNWARDS_ARROW                              = 0x2193,
	LEFT_RIGHT_ARROW                             = 0x2194,
	UP_DOWN_ARROW                                = 0x2195,
	NORTH_WEST_ARROW                             = 0x2196,
	NORTH_EAST_ARROW                             = 0x2197,
	SOUTH_EAST_ARROW                             = 0x2198,
	SOUTH_WEST_ARROW                             = 0x2199,
	LEFTWARDS_ARROW_WITH_STROKE                  = 0x219A,
	RIGHTWARDS_ARROW_WITH_STROKE                 = 0x219B,
	LEFTWARDS_WAVE_ARROW                         = 0x219C,
	RIGHTWARDS_WAVE_ARROW                        = 0x219D,
	LEFTWARDS_TWO_HEADED_ARROW                   = 0x219E,
	UPWARDS_TWO_HEADED_ARROW                     = 0x219F,
	RIGHTWARDS_TWO_HEADED_ARROW                  = 0x21A0,
	DOWNWARDS_TWO_HEADED_ARROW                   = 0x21A1,
	LEFTWARDS_ARROW_WITH_TAIL                    = 0x21A2,
	RIGHTWARDS_ARROW_WITH_TAIL                   = 0x21A3,
	LEFTWARDS_ARROW_FROM_BAR                     = 0x21A4,
	UPWARDS_ARROW_FROM_BAR                       = 0x21A5,
	RIGHTWARDS_ARROW_FROM_BAR                    = 0x21A6,
	DOWNWARDS_ARROW_FROM_BAR                     = 0x21A7,
	UP_DOWN_ARROW_WITH_BASE                      = 0x21A8,
	LEFTWARDS_ARROW_WITH_HOOK                    = 0x21A9,
	RIGHTWARDS_ARROW_WITH_HOOK                   = 0x21AA,
	LEFTWARDS_ARROW_WITH_LOOP                    = 0x21AB,
	RIGHTWARDS_ARROW_WITH_LOOP                   = 0x21AC,
	LEFT_RIGHT_WAVE_ARROW                        = 0x21AD,
	LEFT_RIGHT_ARROW_WITH_STROKE                 = 0x21AE,
	DOWNWARDS_ZIGZAG_ARROW                       = 0x21AF,
	UPWARDS_ARROW_WITH_TIP_LEFTWARDS             = 0x21B0,
	UPWARDS_ARROW_WITH_TIP_RIGHTWARDS            = 0x21B1,
	DOWNWARDS_ARROW_WITH_TIP_LEFTWARDS           = 0x21B2,
	DOWNWARDS_ARROW_WITH_TIP_RIGHTWARDS          = 0x21B3,
	RIGHTWARDS_ARROW_WITH_CORNER_DOWNWARDS       = 0x21B4,
	DOWNWARDS_ARROW_WITH_CORNER_LEFTWARDS        = 0x21B5,
	ANTICLOCKWISE_TOP_SEMICIRCLE_ARROW           = 0x21B6,
	CLOCKWISE_TOP_SEMICIRCLE_ARROW               = 0x21B7,
	NORTH_WEST_ARROW_TO_LONG_BAR                 = 0x21B8,
	LEFTWARDS_ARROW_TO_BAR_OVER_RIGHTWARDS_ARROW_TO_BAR
	                                             = 0x21B9,
	ANTICLOCKWISE_OPEN_CIRCLE_ARROW              = 0x21BA,
	CLOCKWISE_OPEN_CIRCLE_ARROW                  = 0x21BB,
	LEFTWARDS_HARPOON_WITH_BARB_UPWARDS          = 0x21BC,
	LEFTWARDS_HARPOON_WITH_BARB_DOWNWARDS        = 0x21BD,
	UPWARDS_HARPOON_WITH_BARB_RIGHTWARDS         = 0x21BE,
	UPWARDS_HARPOON_WITH_BARB_LEFTWARDS          = 0x21BF,
	RIGHTWARDS_HARPOON_WITH_BARB_UPWARDS         = 0x21C0,
	RIGHTWARDS_HARPOON_WITH_BARB_DOWNWARDS       = 0x21C1,
	DOWNWARDS_HARPOON_WITH_BARB_RIGHTWARDS       = 0x21C2,
	DOWNWARDS_HARPOON_WITH_BARB_LEFTWARDS        = 0x21C3,
	RIGHTWARDS_ARROW_OVER_LEFTWARDS_ARROW        = 0x21C4,
	UPWARDS_ARROW_LEFTWARDS_OF_DOWNWARDS_ARROW   = 0x21C5,
	LEFTWARDS_ARROW_OVER_RIGHTWARDS_ARROW        = 0x21C6,
	LEFTWARDS_PAIRED_ARROWS                      = 0x21C7,
	UPWARDS_PAIRED_ARROWS                        = 0x21C8,
	RIGHTWARDS_PAIRED_ARROWS                     = 0x21C9,
	DOWNWARDS_PAIRED_ARROWS                      = 0x21CA,
	LEFTWARDS_HARPOON_OVER_RIGHTWARDS_HARPOON    = 0x21CB,
	RIGHTWARDS_HARPOON_OVER_LEFTWARDS_HARPOON    = 0x21CC,
	LEFTWARDS_DOUBLE_ARROW_WITH_STROKE           = 0x21CD,
	LEFT_RIGHT_DOUBLE_ARROW_WITH_STROKE          = 0x21CE,
	RIGHTWARDS_DOUBLE_ARROW_WITH_STROKE          = 0x21CF,
	LEFTWARDS_DOUBLE_ARROW                       = 0x21D0,
	UPWARDS_DOUBLE_ARROW                         = 0x21D1,
	RIGHTWARDS_DOUBLE_ARROW                      = 0x21D2,
	DOWNWARDS_DOUBLE_ARROW                       = 0x21D3,
	LEFT_RIGHT_DOUBLE_ARROW                      = 0x21D4,
	UP_DOWN_DOUBLE_ARROW                         = 0x21D5,
	NORTH_WEST_DOUBLE_ARROW                      = 0x21D6,
	NORTH_EAST_DOUBLE_ARROW                      = 0x21D7,
	SOUTH_EAST_DOUBLE_ARROW                      = 0x21D8,
	SOUTH_WEST_DOUBLE_ARROW                      = 0x21D9,
	LEFTWARDS_TRIPLE_ARROW                       = 0x21DA,
	RIGHTWARDS_TRIPLE_ARROW                      = 0x21DB,
	LEFTWARDS_SQUIGGLE_ARROW                     = 0x21DC,
	RIGHTWARDS_SQUIGGLE_ARROW                    = 0x21DD,
	UPWARDS_ARROW_WITH_DOUBLE_STROKE             = 0x21DE,
	DOWNWARDS_ARROW_WITH_DOUBLE_STROKE           = 0x21DF,
	LEFTWARDS_DASHED_ARROW                       = 0x21E0,
	UPWARDS_DASHED_ARROW                         = 0x21E1,
	RIGHTWARDS_DASHED_ARROW                      = 0x21E2,
	DOWNWARDS_DASHED_ARROW                       = 0x21E3,
	LEFTWARDS_ARROW_TO_BAR                       = 0x21E4,
	RIGHTWARDS_ARROW_TO_BAR                      = 0x21E5,
	LEFTWARDS_WHITE_ARROW                        = 0x21E6,
	UPWARDS_WHITE_ARROW                          = 0x21E7,
	RIGHTWARDS_WHITE_ARROW                       = 0x21E8,
	DOWNWARDS_WHITE_ARROW                        = 0x21E9,
	UPWARDS_WHITE_ARROW_FROM_BAR                 = 0x21EA,
	UPWARDS_WHITE_ARROW_ON_PEDESTAL              = 0x21EB,
	UPWARDS_WHITE_ARROW_ON_PEDESTAL_WITH_HORIZONTAL_BAR
	                                             = 0x21EC,
	UPWARDS_WHITE_ARROW_ON_PEDESTAL_WITH_VERTICAL_BAR
	                                             = 0x21ED,
	UPWARDS_WHITE_DOUBLE_ARROW                   = 0x21EE,
	UPWARDS_WHITE_DOUBLE_ARROW_ON_PEDESTAL       = 0x21EF,
	RIGHTWARDS_WHITE_ARROW_FROM_WALL             = 0x21F0,
	NORTH_WEST_ARROW_TO_CORNER                   = 0x21F1,
	SOUTH_EAST_ARROW_TO_CORNER                   = 0x21F2,
	UP_DOWN_WHITE_ARROW                          = 0x21F3,
	RIGHT_ARROW_WITH_SMALL_CIRCLE                = 0x21F4,
	DOWNWARDS_ARROW_LEFTWARDS_OF_UPWARDS_ARROW   = 0x21F5,
	THREE_RIGHTWARDS_ARROWS                      = 0x21F6,
	LEFTWARDS_ARROW_WITH_VERTICAL_STROKE         = 0x21F7,
	RIGHTWARDS_ARROW_WITH_VERTICAL_STROKE        = 0x21F8,
	LEFT_RIGHT_ARROW_WITH_VERTICAL_STROKE        = 0x21F9,
	LEFTWARDS_ARROW_WITH_DOUBLE_VERTICAL_STROKE  = 0x21FA,
	RIGHTWARDS_ARROW_WITH_DOUBLE_VERTICAL_STROKE = 0x21FB,
	LEFT_RIGHT_ARROW_WITH_DOUBLE_VERTICAL_STROKE = 0x21FC,
	LEFTWARDS_OPEN_HEADED_ARROW                  = 0x21FD,
	RIGHTWARDS_OPEN_HEADED_ARROW                 = 0x21FE,
	LEFT_RIGHT_OPEN_HEADED_ARROW                 = 0x21FF,

	// Mathematical Operators
	FOR_ALL                                      = 0x2200,
	UNIVERSAL_QUANTIFIER                         = FOR_ALL,
	COMPLEMENT                                   = 0x2201,
	PARTIAL_DIFFERENTIAL                         = 0x2202,
	THERE_EXISTS                                 = 0x2203,
	EXISTENTIAL_QUANTIFIER                       = 0x2204,
	THERE_DOES_NOT_EXIST                         = 0x2204,
	EMPTY_SET                                    = 0x2205,
	INCREMENT                                    = 0x2206,
	LAPLACE_OPERATOR                             = INCREMENT,
	NABLA                                        = 0x2207,
	GRADIENT                                     = NABLA,
	ELEMENT_OF                                   = 0x2208,
	NOT_AN_ELEMENT_OF                            = 0x2209,
	SMALL_ELEMENT_OF                             = 0x220A,
	CONTAINS_AS_MEMBER                           = 0x220B,
	SUCH_THAT                                    = CONTAINS_AS_MEMBER,
	DOES_NOT_CONTAIN_AS_MEMBER                   = 0x220C,
	SMALL_CONTAINS_AS_MEMBER                     = 0x220D,
	END_OF_PROOF                                 = 0x220E,
	QED                                          = END_OF_PROOF,
	N_ARY_PRODUCT                                = 0x220F,
	N_ARY_COPRODUCT                              = 0x2210,
	N_ARY_SUMMATION                              = 0x2211,
	MINUS_SIGN                                   = 0x2212,
	MINUS_OR_PLUS_SIGN                           = 0x2213,
	DOT_PLUS                                     = 0x2214,
	DIVISION_SLASH                               = 0x2215,
	GENERIC_DIVISION_OPERATOR                    = DIVISION_SLASH,
	SET_MINUS                                    = 0x2216,
	ASTERISK_OPERATOR                            = 0x2217,
	RING_OPERATOR                                = 0x2218,
	COMPOSITE_FUNCTION                           = RING_OPERATOR,
	BULLET_OPERATOR                              = 0x2219,
	SQUARE_ROOT                                  = 0x221A,
	RADICAL_SIGN                                 = SQUARE_ROOT,
	CUBE_ROOT                                    = 0x221B,
	FOURTH_ROOT                                  = 0x221C,
	PROPORTIONAL_TO                              = 0x221D,
	INFINITY                                     = 0x221E,
	RIGHT_ANGLE                                  = 0x221F,
	ANGLE                                        = 0x2220,
	MEASURED_ANGLE                               = 0x2221,
	SPHERICAL_ANGLE                              = 0x2222,
	ANGLE_ARC                                    = SPHERICAL_ANGLE,
	DIVIDES                                      = 0x2223,
	SUCH_THAT_APL                                = DIVIDES,
	DOES_NOT_DIVIDE                              = 0x2224,
	PARALLEL_TO                                  = 0x2225,
	NOT_PARALLEL_TO                              = 0x2226,
	LOGICAL_AND                                  = 0x2227,
	WEDGE                                        = LOGICAL_AND,
	CONJUNCTION                                  = LOGICAL_AND,
	LOGICAL_OR                                   = 0x2228,
	VEE                                          = LOGICAL_OR,
	DISJUNCTION                                  = LOGICAL_OR,
	INTERSECTION                                 = 0x2229,
	UNION                                        = 0x222A,
	INTEGRAL                                     = 0x222B,
	DOUBLE_INTEGRAL                              = 0x222C,
	TRIPLE_INTEGRAL                              = 0x222D,
	CONTOUR_INTEGRAL                             = 0x222E,
	SURFACE_INTEGRAL                             = 0x222F,
	VOLUME_INTEGRAL                              = 0x2230,
	CLOCKWISE_INTEGRAL                           = 0x2231,
	CLOCKWISE_CONTOUR_INTEGRAL                   = 0x2232,
	ANTICLOCKWISE_CONTOUR_INTEGRAL               = 0x2233,
	THEREFORE                                    = 0x2234,
	BECAUSE                                      = 0x2235,
	RATIO                                        = 0x2236,
	PROPORTION                                   = 0x2237,
	DOT_MINUS                                    = 0x2238,
	SATURATING_SUBSTRACTION                      = DOT_MINUS,
	EXCESS                                       = 0x2239,
	GEOMETRIC_PROPORTION                         = 0x223A,
	HOMOTHETIC                                   = 0x223B,
	TILDE_OPERATOR                               = 0x223C,
	VARIES_WITH                                  = TILDE_OPERATOR,
	SIMILAR_TO                                   = TILDE_OPERATOR,
	REVERSED_TILDE                               = 0x223D,
	LAZY_S                                       = REVERSED_TILDE,
	INVERTED_LAZY_S                              = 0x223E,
	MOST_POSITIVE                                = INVERTED_LAZY_S,
	SINE_WAVE                                    = 0x223F,
	ALTERNATING_CURRENT                          = SINE_WAVE,
	WREATH_PRODUCT                               = 0x2240,
	NOT_TILDE                                    = 0x2241,
	MINUS_TILDE                                  = 0x2242,
	ASYMPTOTICALLY_EQUAL_TO                      = 0x2243,
	NOT_ASYMPTOTICALLY_EQUAL_TO                  = 0x2244,
	APPROXIMATELY_EQUAL_TO                       = 0x2245,
	APPROXIMATELY_BUT_NOT_ACTUALLY_EQUAL_TO      = 0x2246,
	NEITHER_APPROXIMATELY_NOR_ACTUALLY_EQUAL_TO  = 0x2247,
	ALMOST_EQUAL_TO                              = 0x2248,
	ASYMPTOTIC_TO                                = ALMOST_EQUAL_TO,
	NOT_ALMOST_EQUAL_TO                          = 0x2249,
	ALMOST_EQUAL_OR_EQUAL_TO                     = 0x224A,
	TRIPLE_TILDE                                 = 0x224B,
	ALL_EQUAL_TO                                 = 0x224C,
	EQUIVALENT_TO                                = 0x224D,
	GEOMETRICALLY_EQUIVALENT_TO                  = 0x224E,
	DIFFERENCE_BETWEEN                           = 0x224F,
	APPROACHES_THE_LIMIT                         = 0x2250,
	GEOMETRICALLY_EQUAL_TO                       = 0x2251,
	APPROXIMATELY_EQUAL_TO_OR_THE_IMAGE_OF       = 0x2252,
	NEARLY_EQUALS                                = APPROXIMATELY_EQUAL_TO_OR_THE_IMAGE_OF,
	IMAGE_OF_OR_APPROXIMATELY_EQUAL_TO           = 0x2253,
	COLON_EQUALS                                 = 0x2254,
	EQUALS_COLON                                 = 0x2255,
	RING_IN_EQUAL_TO                             = 0x2256,
	RING_EQUAL_TO                                = 0x2257,
	CORRESPONDS_TO                               = 0x2258,
	ESTIMATES                                    = 0x2259,
	EQUIANGULAR_TO                               = 0x225A,
	STAR_EQUALS                                  = 0x225B,
	DELTA_EQUAL_TO                               = 0x225C,
	EQUAL_TO_BY_DEFINITION                       = 0x225D,
	MEASURED_BY                                  = 0x225E,
	QUESTIONES_EQUAL_TO                          = 0x225F,
	NOT_EQUAL_TO                                 = 0x2260,
	IDENTICAL_TO                                 = 0x2261,
	NOT_IDENTICAL_TO                             = 0x2262,
	STRICTLY_EQUIVALENT_TO                       = 0x2263,
	LESS_THAN_OR_EQUAL_TO                        = 0x2264,
	GREATER_THAN_OR_EQUAL_TO                     = 0x2265,
	LESS_THAN_OVER_EQUAL_TO                      = 0x2266,
	GREATER_THAN_OVER_EQUAL_TO                   = 0x2267,
	LESS_THAN_BUT_NOT_EQUAL_TO                   = 0x2268,
	GREATER_THAN_BUT_NOT_EQUAL_TO                = 0x2269,
	MUCH_LESS_THAN                               = 0x226A,
	MUCH_GREATER_THAN                            = 0x226B,
	BETWEEN                                      = 0x226C,
	PLAINTIFF                                    = BETWEEN,
	QUANTIC                                      = BETWEEN,
	NOT_EQUIVALENT_TO                            = 0x226D,
	NOT_LESS_THAN                                = 0x226E,
	NOT_GREATER_THAN                             = 0x226F,
	NEITHER_LESS_THAN_NOR_EQUAL_TO               = 0x2270,
	NEITHER_GREATER_THAN_NOR_EQUAL_TO            = 0x2271,
	LESS_THAN_OR_EQUIVALENT_TO                   = 0x2272,
	GREATER_THAN_OR_EQUIVALENT_TO                = 0x2273,
	NEITHER_LESS_THAN_NOR_EQUIVALENT_TO          = 0x2274,
	NEITHER_GREATER_THAN_NOR_EQUIVALENT_TO       = 0x2275,
	LESS_THAN_OR_GREATER_THAN                    = 0x2276,
	GREATER_THAN_OR_LESS_THAN                    = 0x2277,
	NEITHER_LESS_THAN_NOR_GREATER_THAN           = 0x2278,
	NEITHER_GREATER_THAN_NOR_LESS_THAN           = 0x2279,
	PRECEDES                                     = 0x227A,
	LOWER_RANK_THAN                              = PRECEDES,
	SUCCEEDS                                     = 0x227B,
	HIGHER_RANK_THAN                             = SUCCEEDS,
	PRECEDES_OR_EQUAL_TO                         = 0x227C,
	SUCCEEDS_OR_EQUAL_TO                         = 0x227D,
	PRECEDES_OR_EQUIVALENT_TO                    = 0x227E,
	SUCCEEDS_OR_EQUIVALENT_TO                    = 0x227F,
	DOES_NOT_PRECEDE                             = 0x2280,
	DOES_NOT_SUCCEED                             = 0x2281,
	SUBSET_OF                                    = 0x2282,
	INCLUDED_IN_SET                              = SUBSET_OF,
	SUPERSET_OF                                  = 0x2283,
	INCLUDES_IN_SET                              = SUPERSET_OF,
	NOT_A_SUBSET_OF                              = 0x2284,
	NOT_A_SUPERSET_OF                            = 0x2285,
	SUBSET_OF_OR_EQUAL_TO                        = 0x2286,
	SUPERSET_OF_OR_EQUAL_TO                      = 0x2287,
	NEITHER_A_SUBSET_OF_NOR_EQUAL_TO             = 0x2288,
	NEITHER_A_SUPERSET_OF_NOR_EQUAL_TO           = 0x2289,
	SUBSET_OF_WITH_NOT_EQUAL_TO                  = 0x228A,
	SUPERSET_OF_WITH_NOT_EQUAL_TO                = 0x228B,
	MULTISET                                     = 0x228C,
	MULTISET_MULTIPLICATION                      = 0x228D,
	MULTISET_UNION                               = 0x228E,
	SQUARE_IMAGE_OF                              = 0x228F,
	SQUARE_ORIGINAL_OF                           = 0x2290,
	SQUARE_IMAGE_OF_OR_EQUAL_TO                  = 0x2291,
	SQUARE_ORIGINAL_OF_OR_EQUAL_TO               = 0x2292,
	SQUARE_CAP                                   = 0x2293,
	SQUARE_CUP                                   = 0x2294,
	CIRCLED_PLUS                                 = 0x2295,
	DIRECT_SUM                                   = CIRCLED_PLUS,
	CIRCLED_MINUS                                = 0x2296,
	SYMMETRIC_DIFFERENCE                         = CIRCLED_MINUS,
	CIRCLED_TIMES                                = 0x2297,
	TENSOR_PRODUCT                               = CIRCLED_TIMES,
	CIRCLED_DIVISION_SLASH                       = 0x2298,
	CIRCLED_DOT_OPERATOR                         = 0x2299,
	CIRCLED_RING_OPERATOR                        = 0x229A,
	CIRCLED_ASTERISK_OPERATOR                    = 0x229B,
	CIRCLED_EQUALS                               = 0x229C,
	CIRCLED_DASH                                 = 0x229D,
	SQUARED_PLUS                                 = 0x229E,
	SQUARED_MINUS                                = 0x229F,
	SQUARED_TIMES                                = 0x22A0,
	SQUARED_DOT_OPERATOR                         = 0x22A1,
	RIGHT_TACK                                   = 0x22A2,
	TURNSTILE                                    = RIGHT_TACK,
	PROVES                                       = RIGHT_TACK,
	IMPLIES                                      = RIGHT_TACK,
	YIELDS                                       = RIGHT_TACK,
	REDUCIBLE                                    = RIGHT_TACK,
	LEFT_TACK                                    = 0x22A3,
	REVERSE_TURNSTILE                            = LEFT_TACK,
	NON_THEOREM                                  = LEFT_TACK,
	DOES_NOT_YIELD                               = LEFT_TACK,
	DOWN_TACK                                    = 0x22A4,
	TOP                                          = DOWN_TACK,
	UP_TACK                                      = 0x22A5,
	BASE                                         = UP_TACK,
	BOTTOM                                       = UP_TACK,
	ASSERTION                                    = 0x22A6,
	REDUCES_TO                                   = ASSERTION,
	MODELS                                       = 0x22A7,
	VALID                                        = 0x22A8,
	IS_TRUE                                      = VALID,
	STATEMENT_IS_TRUE                            = VALID,
	IS_A_TAUTOLOGY                               = VALID,
	SATISFIES                                    = VALID,
	RESULTS_IN                                   = VALID,
	FORCES                                       = 0x22A9,
	TRIPLE_VERTICAL_BAR_RIGHT_TURNSTILE          = 0x22AA,
	DOUBLE_VERTICAL_BAR_DOUBLE_RIGHT_TURNSTILE   = 0x22AB,
	DOES_NOT_PROVE                               = 0x22AC,
	NOT_TRUE                                     = 0x22AD,
	DOES_NOT_FORCE                               = 0x22AE,
	NEGATED_DOUBLE_VERTICAL_BAR_DOUBLE_RIGHT_TURNSTILE
	                                             = 0x22AF,
	PRECEDES_UNDER_RELATION                      = 0x22B0,
	SUCCEEDS_UNDER_RELATION                      = 0x22B1,
	NORMAL_SUBGROUP_OF                           = 0x22B2,
	CONTAINS_AS_NORMAL_SUBGROUP                  = 0x22B3,
	NORMAL_SUBGROUP_OF_OF_EQUAL_TO               = 0x22B4,
	CONTAINS_AS_NORMAL_SUBGROUP_OR_EQUAL_TO      = 0x22B5,
	ORIGINAL_OF                                  = 0x22B6,
	IMAGE_OF                                     = 0x22B7,
	MULTIMAP                                     = 0x22B8,
	HERMITIAN_CONJUGATE_MATRIX                   = 0x22B9,
	INTERCALATE                                  = 0x22BA,
	XOR                                          = 0x22BB,
	NAND                                         = 0x22BC,
	NOR                                          = 0x22BD,
	RIGHT_ANGLE_WITH_ARC                         = 0x22BE,
	RIGHT_TRIANGLE                               = 0x22BF,
	N_ARY_LOGICAL_AND                            = 0x22C0,
	N_ARY_LOGICAL_OR                             = 0x22C1,
	N_ARY_INTERSECTION                           = 0x22C2,
	N_ARY_UNION                                  = 0x22C3,
	DIAMOND_OPERATOR                             = 0x22C4,
	DOT_OPERATOR                                 = 0x22C5,
	STAR_OPERATOR                                = 0x22C6,
	DIVISION_TIMES                               = 0x22C7,
	BOWTIE                                       = 0x22C8,
	LEFT_NORMAL_FACTOR_SEMIDIRECT_PRODUCT        = 0x22C9,
	RIGHT_NORMAL_FACTOR_SEMIDIRECT_PRODUCT       = 0x22CA,
	LEFT_SEMIDIRECT_PRODUCT                      = 0x22CB,
	RIGHT_SEMIDIRECT_PRODUCT                     = 0x22CC,
	REVERSED_TILDE_EQUALS                        = 0x22CD,
	CURLY_LOGICAL_OR                             = 0x22CE,
	CURLY_LOGICAL_AND                            = 0x22CF,
	DOUBLE_SUBSET                                = 0x22D0,
	DOUBLE_SUPERSET                              = 0x22D1,
	DOUBLE_INTERSECTION                          = 0x22D2,
	DOUBLE_UNION                                 = 0x22D3,
	PITCHFORK                                    = 0x22D4,
	PROPER_INTERSECTION                          = PITCHFORK,
	EQUAL_AND_PARALLEL_TO                        = 0x22D5,
	LESS_THAN_WITH_DOT                           = 0x22D6,
	GREATER_THAN_WITH_DOT                        = 0x22D7,
	VERY_MUCH_LESS_THAN                          = 0x22D8,
	VERY_MUCH_GREATER_THAN                       = 0x22D9,
	LESS_THAN_EQUAL_TO_OR_GREATER_THAN           = 0x22DA,
	GREATER_THAN_EQUAL_TO_OR_LESS_THAN           = 0x22DB,
	EQUAL_TO_OR_LESS_THAN                        = 0x22DC,
	EQUAL_TO_OR_GREATER_THAN                     = 0x22DD,
	EQUAL_TO_OR_PRECEDES                         = 0x22DE,
	EQUAL_TO_OR_SUCCEEDS                         = 0x22DF,
	DOES_NOT_PRECEDE_OR_EQUAL                    = 0x22E0,
	DOES_NOT_SUCCEED_OR_EQUAL                    = 0x22E1,
	NOT_SQUARE_IMAGE_OF_OR_EQUAL_TO              = 0x22E2,
	NOT_SQUARE_ORIGINAL_OF_OR_EQUAL_TO           = 0x22E3,
	SQUARE_IMAGE_OF_OR_NOT_EQUAL_TO              = 0x22E4,
	SQUARE_ORIGINAL_OF_OR_NOT_EQUAL_TO           = 0x22E5,
	LESS_THAN_BUT_NOT_EQUIVALENT_TO              = 0x22E6,
	GREATER_THAN_BUT_NOT_EQUIVALENT_TO           = 0x22E7,
	PRECEDES_BUT_NOT_EQUIVALENT_TO               = 0x22E8,
	SUCCEEDS_BUT_NOT_EQUIVALENT_TO               = 0x22E9,
	NOT_NORMAL_SUBGROUP_OF                       = 0x22EA,
	DOES_NOT_CONTAIN_AS_NORMAL_SUBGROUP          = 0x22EB,
	NOT_NORMAL_SUBGROUP_OF_OR_EQUAL_TO           = 0x22EC,
	DOES_NOT_CONTAIN_AS_NORMAL_SUBGROUP_OR_EQUAL = 0x22ED,
	VERTICAL_ELLIPSIS                            = 0x22EE,
	MIDLINE_HORIZONTAL_ELLIPSIS                  = 0x22EF,
	UP_RIGHT_DIAGONAL_ELLIPSIS                   = 0x22F0,
	DOWN_RIGHT_DIAGONAL_ELLIPSIS                 = 0x22F1,
	ELEMENT_OF_WITH_LONG_HORIZONTAL_STROKE       = 0x22F2,
	ELEMENT_OF_WITH_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE
	                                             = 0x22F3,
	SMALL_ELEMENT_OF_WITH_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE
	                                             = 0x22F4,
	ELEMENT_OF_WITH_DOT_ABOBE                    = 0x22F5,
	ELEMENT_OF_WITH_OVERBAR                      = 0x22F6,
	SMALL_ELEMENT_OF_WITH_OVERBAR                = 0x22F7,
	ELEMENT_OF_WITH_UNDERBAR                     = 0x22F8,
	ELEMENT_OF_WITH_TWO_HORIZONTAL_STROKES       = 0x22F9,
	CONTAINS_WITH_LONG_HORIZONTAL_STROKE         = 0x22FA,
	CONTAINS_WITH_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE
	                                             = 0x22FB,
	SMALL_CONTAINS_WITH_VERTICAL_BAR_AT_END_OF_HORIZONTAL_STROKE
	                                             = 0x22FC,
	CONTAINS_WITH_OVERBAR                        = 0x22FD,
	SMALL_CONTAINS_WITH_OVERBAR                  = 0x22FE,
	Z_NOTATION_BAG_MEMBERSHIP                    = 0x22FF,

	// Geometric Shapes
	BLACK_SQUARE                                 = 0x25A0,
	WHITE_SQUARE                                 = 0x25A1,
	WHITE_SQUARE_WITH_ROUNDED_CORNERS            = 0x25A2,
	WHITE_SQUARE_CONTAINING_BLACK_SMALL_SQUARE   = 0x25A3,
	SQUARE_WITH_HORIZONTAL_FILL                  = 0x25A4,
	SQUARE_WITH_VERTICAL_FILL                    = 0x25A5,
	SQUARE_WITH_ORTHOGONAL_CROSSHATCH_FILL       = 0x25A6,
	SQUARE_WITH_UPPER_LEFT_TO_LOWER_RIGHT_FILL   = 0x25A7,
	SQUARE_WITH_UPPER_RIGHT_TO_LOWER_LEFT_FILL   = 0x25A8,
	SQUARE_WITH_DIAGONAL_CROSSHATCH_FILL         = 0x25A9,
	BLACK_SMALL_SQUARE                           = 0x25AA,
	WHITE_SMALL_SQUARE                           = 0x25AB,
	BLACK_RECTANGLE                              = 0x25AC,
	WHITE_RECTANGLE                              = 0x25AD,
	BLACK_VERTICAL_RECTANGLE                     = 0x25AE,
	WHITE_VERTICAL_RECTANGLE                     = 0x25AF,
	BLACK_PARALLELOGRAM                          = 0x25B0,
	WHITE_PARALLELOGRAM                          = 0x25B1,
	BLACK_UP_POINTING_TRIANGLE                   = 0x25B2,
	WHITE_UP_POINTING_TRIANGLE                   = 0x25B3,
	BLACK_UP_POINTING_SMALL_TRIANGLE             = 0x25B4,
	WHITE_UP_POINTING_SMALL_TRIANGLE             = 0x25B5,
	BLACK_RIGHT_POINTING_TRIANGLE                = 0x25B6,
	WHITE_RIGHT_POINTING_TRIANGLE                = 0x25B7,
	BLACK_RIGHT_POINTING_SMALL_TRIANGLE          = 0x25B8,
	WHITE_RIGHT_POINTING_SMALL_TRIANGLE          = 0x25B9,
	BLACK_RIGHT_POINTING_POINTER                 = 0x25BA,
	WHITE_RIGHT_POINTING_POINTER                 = 0x25BB,
	BLACK_DOWN_POINTING_TRIANGLE                 = 0x25BC,
	WHITE_DOWN_POINTING_TRIANGLE                 = 0x25BD,
	BLACK_DOWN_POINTING_SMALL_TRIANGLE           = 0x25BE,
	WHITE_DOWN_POINTING_SMALL_TRIANGLE           = 0x25BF,
	BLACK_LEFT_POINTING_TRIANGLE                 = 0x25C0,
	WHITE_LEFT_POINTING_TRIANGLE                 = 0x25C1,
	BLACK_LEFT_POINTING_SMALL_TRIANGLE           = 0x25C2,
	WHITE_LEFT_POINTING_SMALL_TRIANGLE           = 0x25C3,
	BLACK_LEFT_POINTING_POINTER                  = 0x25C4,
	WHITE_LEFT_POINTING_POINTER                  = 0x25C5,
	BLACK_DIAMOND                                = 0x25C6,
	WHITE_DIAMOND                                = 0x25C7,
	WHITE_DIAMOND_CONTAINING_BLACK_SMALL_DIAMOND = 0x25C8,
	FISHEYE                                      = 0x25C9,
	LOZENGE                                      = 0x25CA,
	WHITE_CIRCLE                                 = 0x25CB,
	DOTTED_CIRCLE                                = 0x25CC,
	CIRCLE_WITH_VERTICAL_FILL                    = 0x25CD,
	BULLSEYE                                     = 0x25CE,
	BLACK_CIRCLE                                 = 0x25CF,
	CIRCLE_WITH_LEFT_HALF_BLACK                  = 0x25D0,
	CIRCLE_WITH_RIGHT_HALF_BLACK                 = 0x25D1,
	CIRCLE_WITH_LOWER_HALF_BLACK                 = 0x25D2,
	CIRCLE_WITH_UPPER_HALF_BLACK                 = 0x25D3,
	CIRCLE_WITH_UPPER_RIGHT_QUADRANT_BLACK       = 0x25D4,
	CIRCLE_WITH_ALL_BUT_UPPER_LEFT_QUADRANT_BLACK
	                                             = 0x25D5,
	LEFT_HALF_BLACK_CIRCLE                       = 0x25D6,
	RIGHT_HALF_BLACK_CIRCLE                      = 0x25D7,
	INVERSE_BULLET                               = 0x25D8,
	INVERSE_WHITE_CIRCLE                         = 0x25D9,
	UPPER_HALF_INVERSE_WHITE_CIRCLE              = 0x25DA,
	LOWER_HALF_INVERSE_WHITE_CIRCLE              = 0x25DB,
	UPPER_LEFT_QUADRANT_CIRCULAR_ARC             = 0x25DC,
	UPPER_RIGHT_QUADRANT_CIRCULAR_ARC            = 0x25DD,
	LOWER_RIGHT_QUADRANT_CIRCULAR_ARC            = 0x25DE,
	LOWER_LEFT_QUADRANT_CIRCULAR_ARC             = 0x25DF,
	UPPER_HALF_CIRCLE                            = 0x25E0,
	LOWER_HALF_CIRCLE                            = 0x25E1,
	BLACK_LOWER_RIGHT_TRIANGLE                   = 0x25E2,
	BLACK_LOWER_LEFT_TRIANGLE                    = 0x25E3,
	BLACK_UPPER_LEFT_TRIANGLE                    = 0x25E4,
	BLACK_UPPER_RIGHT_TRIANGLE                   = 0x25E5,
	WHITE_BULLET                                 = 0x25E6,
	SQUARE_WITH_LEFT_HALF_BLACK                  = 0x25E7,
	SQUARE_WITH_RIGHT_HALF_BLACK                 = 0x25E8,
	SQUARE_WITH_UPPER_LEFT_DIAGONAL_HALF_BLACK   = 0x25E9,
	SQUARE_WITH_LOWER_RIGHT_DIAGONAL_HALF_BLACK  = 0x25EA,
	WHITE_SQUARE_WITH_VERTICAL_BISECTING_LINE    = 0x25EB,
	WHITE_UP_POINTING_TRIANGLE_WITH_DOT          = 0x25EC,
	UP_POINTING_TRIANGLE_WITH_LEFT_HALF_BLACK    = 0x25ED,
	UP_POINTING_TRIANGLE_WITH_RIGHT_HALF_BLACK   = 0x25EE,
	LARGE_CIRCLE                                 = 0x25EF,
	WHITE_SQUARE_WITH_UPPER_LEFT_QUADRANT        = 0x25F0,
	WHITE_SQUARE_WITH_LOWER_LEFT_QUADRANT        = 0x25F1,
	WHITE_SQUARE_WITH_LOWER_RIGHT_QUADRANT       = 0x25F2,
	WHITE_SQUARE_WITH_UPPER_RIGHT_QUADRANT       = 0x25F3,
	WHITE_CIRCLE_WITH_UPPER_LEFT_QUADRANT        = 0x25F4,
	WHITE_CIRCLE_WITH_LOWER_LEFT_QUADRANT        = 0x25F5,
	WHITE_CIRCLE_WITH_LOWER_RIGHT_QUADRANT       = 0x25F6,
	WHITE_CIRCLE_WITH_UPPER_RIGHT_QUADRANT       = 0x25F7,
	UPPER_LEFT_TRIANGLE                          = 0x25F8,
	UPPER_RIGHT_TRIANGLE                         = 0x25F9,
	LOWER_LEFT_TRIANGLE                          = 0x25FA,
	WHITE_MEDIUM_SQUARE                          = 0x25FB,
	ALWAYS                                       = WHITE_MEDIUM_SQUARE,
	ALWAYS_MODAL_OPERATOR                        = WHITE_MEDIUM_SQUARE,
	BLACK_MEDIUM_SQUARE                          = 0x25FC,
	WHITE_MEDIUM_SMALL_SQUARE                    = 0x25FD,
	BLACK_MEDIUM_SMALL_SQUARE                    = 0x25FE,
	LOWER_RIGHT_TRIANGLE                         = 0x25FF,

	// Dingbats
	HEAVY_WIDE_HEADED_RIGHTWARDS_ARROW           = 0x2794,
	HEAVY_PLUS_SIGN                              = 0x2795,
	HEAVY_MINUS_SIGN                             = 0x2796,
	HEAVY_DIVISION_SIGN                          = 0x2797,

	// Miscellaneous Mathematical Symbols-A
	THREE_DIMENSIONAL_ANGLE                      = 0x27C0,
	WHITE_TRIANGLE_CONTAINING_SMALL_WHITE_TRIANGLE
	                                             = 0x27C1,
	PERPENDICULAR                                = 0x27C2,
	OPEN_SUBSET                                  = 0x27C3,
	OPEN_SUPERSET                                = 0x27C4,
	LEFT_S_SHAPED_BAG_DELIMITER                  = 0x27C5,
	RIGHT_S_SHAPED_BAG_DELIMITER                 = 0x27C6,
	OR_WITH_DOT_INSIDE                           = 0x27C7,
	REVERSE_SOLIDUS_PRECEDING_SUBSET             = 0x27C8,
	SUPERSET_PRECEDING_SOLIDUS                   = 0x27C9,
	VERTICAL_BAR_WITH_HORIZONTAL_STROKE          = 0x27CA,
	MATHEMATICAL_RISING_DIAGONAL                 = 0x27CB,
	LONG_DIVISION                                = 0x27CC,
	MATHEMATICAL_FALLING_DIAGONAL                = 0x27CD,
	SQUARED_LOGICAL_AND                          = 0x27CE,
	SQUARED_LOGICAL_OR                           = 0x27CF,
	WHITE_DIAMOND_WITH_CENTRED_DOT               = 0x27D0,
	AND_WITH_DOT                                 = 0x27D1,
	ELEMENT_OF_OPENING_UPWARDS                   = 0x27D2,
	LOWER_RIGHT_CORNER_WITH_DOT                  = 0x27D3,
	UPPER_LEFT_CORNER_WITH_DOT                   = 0x27D4,
	LEFT_OUTER_JOIN                              = 0x27D5,
	RIGHT_OUTER_JOIN                             = 0x27D6,
	FULL_OUTER_JOIN                              = 0x27D7,
	LARGE_UP_TACK                                = 0x27D8,
	LARGE_DOWN_TACK                              = 0x27D9,
	LEFT_AND_RIGHT_DOUBLE_TURNSTILE              = 0x27DA,
	LEFT_AND_RIGHT_TACK                          = 0x27DB,
	LEFT_MULTIMAP                                = 0x27DC,
	LONG_RIGHT_TACK                              = 0x27DD,
	LONG_LEFT_TACK                               = 0x27DE,
	UP_TACK_WITH_CIRCLE_ABOVE                    = 0x27DF,
	LOZENGE_DIVIDED_BY_HORIZONTAL_RULE           = 0x27E0,
	WHITE_CONCAVE_SIDED_DIAMOND                  = 0x27E1,
	WHITE_CONCAVE_SIDED_DIAMOND_WITH_LEFTWARDS_TICK
	                                             = 0x27E2,
	WHITE_CONCAVE_SIDED_DIAMOND_WITH_RIGHTWARDS_TICK
	                                             = 0x27E3,
	WHITE_SQUARE_WITH_LEFTWARDS_TICK             = 0x27E4,
	WHITE_SQUARE_WITH_RIGHTWARDS_TICK            = 0x27E5,
	MATHEMATICAL_LEFT_WHITE_SQUARE_BRACKET       = 0x27E6,
	MATHEMATICAL_RIGHT_WHITE_SQUARE_BRACKET      = 0x27E7,
	MATHEMATICAL_LEFT_ANGLE_BRACKET              = 0x27E8,
	MATHEMATICAL_RIGHT_ANGLE_BRACKET             = 0x27E9,
	MATHEMATICAL_LEFT_DOUBLE_ANGLE_BRACKET       = 0x27EA,
	MATHEMATICAL_RIGHT_DOUBLE_ANGLE_BRACKET      = 0x27EB,
	MATHEMATICAL_LEFT_WHITE_TORTOISE_SHELL_BRACKET
	                                             = 0x27EC,
	MATHEMATICAL_RIGHT_WHITE_TORTOISE_SHELL_BRACKET
	                                             = 0x27ED,
	MATHEMATICAL_LEFT_FLATTENED_PARENTHESIS      = 0x27EE,
	MATHEMATICAL_RIGHT_FLATTENED_PARENTHESIS     = 0x27EF,

	// Supplemental Arrows-A 27Fx
	UPWARDS_QUADRUPLE_ARROW                      = 0x27F0,
	DOWNWARDS_QUADRUPLE_ARROW                    = 0x27F1,
	ANTICLOCKWISE_GAPPED_CIRCLE_ARROW            = 0x27F2,
	CLOCKWISE_GAPPED_CIRCLE_ARROW                = 0x27F3,
	RIGHT_ARROW_WITH_CIRCLED_PLUS                = 0x27F4,
	LONG_LEFTWARDS_ARROW                         = 0x27F5,
	LONG_RIGHTWARDS_ARROW                        = 0x27F6,
	LONG_LEFT_RIGHT_ARROW                        = 0x27F7,
	LONG_LEFTWARDS_DOUBLE_ARROW                  = 0x27F8,
	LONG_RIGHTWARDS_DOUBLE_ARROW                 = 0x27F9,
	LONG_LEFT_RIGHT_DOUBLE_ARROW                 = 0x27FA,
	LONG_LEFTWARDS_ARROW_FROM_BAR                = 0x27FB,
	LONG_RIGHTWARDS_ARROW_FROM_BAR               = 0x27FC,
	LONG_LEFTWARDS_DOUBLE_ARROW_FROM_BAR         = 0x27FD,
	LONG_RIGHTWARDS_DOUBLE_ARROW_FROM_BAR        = 0x27FE,
	LONG_RIGHTWARDS_SQUIGGLE_ARROW               = 0x27FF,

	// Supplemental Arrows-B 2900-297F
	RIGHTWARDS_TWO_HEADED_ARROW_WITH_VERTICAL_STROKE
	                                             = 0x2900,
	RIGHTWARDS_TWO_HEADED_ARROW_WITH_DOUBLE_VERTICAL_STROKE
	                                             = 0x2901,
	LEFTWARDS_DOUBLE_ARROW_WITH_VERTICAL_STROKE  = 0x2902,
	RIGHTWARDS_DOUBLE_ARROW_WITH_VERTICAL_STROKE = 0x2903,
	LEFT_RIGHT_DOUBLE_ARROW_WITH_VERTICAL_STROKE = 0x2904,
	RIGHTWARDS_TWO_HEADED_ARROW_FROM_BAR         = 0x2905,
	LEFTWARDS_DOUBLE_ARROW_FROM_BAR              = 0x2906,
	RIGHTWARDS_DOUBLE_ARROW_FROM_BAR             = 0x2907,
	DOWNWARDS_ARROW_WITH_HORIZONTAL_STROKE       = 0x2908,
	UPWARDS_ARROW_WITH_HORIZONTAL_STROKE         = 0x2909,
	UPWARDS_TRIPLE_ARROW                         = 0x290A,
	DOWNWARDS_TRIPLE_ARROW                       = 0x290B,
	LEFTWARDS_DOUBLE_DASH_ARROW                  = 0x290C,
	RIGHTWARDS_DOUBLE_DASH_ARROW                 = 0x290D,
	LEFTWARDS_TRIPLE_DASH_ARROW                  = 0x290E,
	RIGHTWARDS_TRIPLE_DASH_ARROW                 = 0x290F,
	RIGHTWARDS_TWO_HEADED_TRIPLE_DASH_ARROW      = 0x2910,
	RIGHTWARDS_ARROW_WITH_DOTTED_STEM            = 0x2911,
	UPWARDS_ARROW_TO_BAR                         = 0x2912,
	DOWNWARDS_ARROW_TO_BAR                       = 0x2913,
	RIGHTWARDS_ARROW_WITH_TAIL_WITH_VERTICAL_STROKE
	                                             = 0x2914,
	RIGHTWARDS_ARROW_WITH_TAIL_WITH_DOUBLE_VERTICAL_STROKE
	                                             = 0x2915,
	RIGHTWARDS_TWO_HEADED_ARROW_WITH_TAIL        = 0x2916,
	RIGHTWARDS_TWO_HEADED_ARROW_WITH_TAIL_WITH_VERTICAL_STROKE
	                                             = 0x2917,
	RIGHTWARDS_TWO_HEADED_ARROW_WITH_TAIL_WITH_DOUBLE_VERTICAL_STROKE
	                                             = 0x2918,
	LEFTWARDS_ARROW_TAIL                         = 0x2919,
	RIGHTWARDS_ARROW_TAIL                        = 0x291A,
	LEFTWARDS_DOUBLE_ARROW_TAIL                  = 0x291B,
	RIGHTWARDS_DOUBLE_ARROW_TAIL                 = 0x291C,
	LEFTWARDS_ARROW_TO_BLACK_DIAMOND             = 0x291D,
	RIGHTWARDS_ARROW_TO_BLACK_DIAMOND            = 0x291E,
	LEFTWARDS_ARROW_FROM_BAR_TO_BLACK_DIAMOND    = 0x291F,
	RIGHTWARDS_ARROW_FROM_BAR_TO_BLACK_DIAMOND   = 0x2920,
	NORTH_WEST_AND_SOUTH_EAST_ARROW              = 0x2921,
	NORTH_EAST_AND_SOUTH_WEST_ARROW              = 0x2922,
	NORTH_WEST_ARROW_WITH_HOOK                   = 0x2923,
	NORTH_EAST_ARROW_WITH_HOOK                   = 0x2924,
	SOUTH_EAST_ARROW_WITH_HOOK                   = 0x2925,
	SOUTH_WEST_ARROW_WITH_HOOK                   = 0x2926,
	NORTH_WEST_ARROW_AND_NORTH_EAST_ARROW        = 0x2927,
	NORTH_EAST_ARROW_AND_SOUTH_EAST_ARROW        = 0x2928,
	SOUTH_EAST_ARROW_AND_SOUTH_WEST_ARROW        = 0x2929,
	SOUTH_WEST_ARROW_AND_NORTH_WEST_ARROW        = 0x292A,
	RISING_DIAGONAL_CROSSING_FALLING_DIAGONAL    = 0x292B,
	FALLING_DIAGONAL_CROSSING_RISING_DIAGONAL    = 0x292C,
	SOUTH_EAST_ARROW_CROSSING_NORTH_EAST_ARROW   = 0x292D,
	NORTH_EAST_ARROW_CROSSING_SOUTH_EAST_ARROW   = 0x292E,
	FALLING_DIAGONAL_CROSSING_NORTH_EAST_ARROW   = 0x292F,
	RISING_DIAGONAL_CROSSING_SOUTH_EAST_ARROW    = 0x2930,
	NORTH_EAST_ARROW_CROSSING_NORTH_WEST_ARROW   = 0x2931,
	NORTH_WEST_ARROW_CROSSING_NORTH_EAST_ARROW   = 0x2932,
	WAVE_ARROW_POINTING_DIRECTLY_RIGHT           = 0x2933,
	ARROW_POINTING_RIGHTWARDS_THEN_CURVING_UPWARDS
	                                             = 0x2934,
	ARROW_POINTING_RIGHTWARDS_THEN_CURVING_DOWNWARDS
	                                             = 0x2935,
	ARROW_POINTING_DOWNWARDS_THEN_CURVING_LEFTWARDS
	                                             = 0x2936,
	ARROW_POINTING_DOWNWARDS_THEN_CURVING_RIGHTWARDS
	                                             = 0x2937,
	RIGHT_SIDE_ARC_CLOCKWISE_ARROW               = 0x2938,
	LEFT_SIDE_ARC_ANTICLOCKWISE_ARROW            = 0x2939,
	TOP_ARC_ANTICLOCKWISE_ARROW                  = 0x293A,
	BOTTOM_ARC_ANTICLOCKWISE_ARROW               = 0x293B,
	TOP_ARC_CLOCKWISE_ARROW_WITH_MINUS           = 0x293C,
	TOP_ARC_ANTICLOCKWISE_ARROW_WITH_PLUS        = 0x293D,
	LOWER_RIGHT_SEMICIRCULAR_CLOCKWISE_ARROW     = 0x293E,
	LOWER_LEFT_SEMICIRCULAR_ANTICLOCKWISE_ARROW  = 0x293F,
	ANTICLOCKWISE_CLOSED_CIRCLE_ARROW            = 0x2940,
	CLOCKWISE_CLOSED_CIRCLE_ARROW                = 0x2941,
	RIGHTWARDS_ARROW_ABOVE_SHORT_LEFTWARDS_ARROW = 0x2942,
	LEFTWARDS_ARROW_ABOVE_SHORT_RIGHTWARDS_ARROW = 0x2943,
	SHORT_RIGHTWARDS_ARROW_ABOVE_LEFTWARDS_ARROW = 0x2944,
	RIGHTWARDS_ARROW_WITH_PLUS_BELOW             = 0x2945,
	LEFTWARDS_ARROW_WITH_PLUS_BELOW              = 0x2946,
	RIGHTWARDS_ARROW_THROUGH_X                   = 0x2947,
	LEFT_RIGHT_ARROW_THROUGH_SMALL_CIRCLE        = 0x2948,
	UPWARDS_TWO_HEADED_ARROW_FROM_SMALL_CIRCLE   = 0x2949,
	LEFT_BARB_UP_RIGHT_BARB_DOWN_HARPOON         = 0x294A,
	LEFT_BARB_DOWN_RIGHT_BARB_UP_HARPOON         = 0x294B,
	UP_BARB_RIGHT_DOWN_BARB_LEFT_HARPOON         = 0x294C,
	UP_BARB_LEFT_DOWN_BARB_RIGHT_HARPOON         = 0x294D,
	LEFT_BARB_UP_RIGHT_BARB_UP_HARPOON           = 0x294E,
	UP_BARB_RIGHT_DOWN_BARB_RIGHT_HARPOON        = 0x294F,
	LEFT_BARB_DOWN_RIGHT_BARB_DOWN_HARPOON       = 0x2950,
	UP_BARB_LEFT_DOWN_BARB_LEFT_HARPOON          = 0x2951,
	LEFTWARDS_HARPOON_WITH_BARB_UP_TO_BAR        = 0x2952,
	RIGHTWARDS_HARPOON_WITH_BARB_UP_TO_BAR       = 0x2953,
	UPWARDS_HARPOON_WITH_BARB_RIGHT_TO_BAR       = 0x2954,
	DOWNWARDS_HARPOON_WITH_BARB_RIGHT_TO_BAR     = 0x2955,
	LEFTWARDS_HARPOON_WITH_BARB_DOWN_TO_BAR      = 0x2956,
	RIGHTWARDS_HARPOON_WITH_BARB_DOWN_TO_BAR     = 0x2957,
	UPWARDS_HARPOON_WITH_BARB_LEFT_TO_BAR        = 0x2958,
	DOWNWARDS_HARPOON_WITH_BARB_LEFT_TO_BAR      = 0x2959,
	LEFTWARDS_HARPOON_WITH_BARB_UP_FROM_BAR      = 0x295A,
	RIGHTWARDS_HARPOON_WITH_BARB_UP_FROM_BAR     = 0x295B,
	UPWARDS_HARPOON_WITH_BARB_RIGHT_FROM_BAR     = 0x295C,
	DOWNWARDS_HARPOON_WITH_BARB_RIGHT_FROM_BAR   = 0x295D,
	LEFTWARDS_HARPOON_WITH_BARB_DOWN_FROM_BAR    = 0x295E,
	RIGHTWARDS_HARPOON_WITH_BARB_DOWN_FROM_BAR   = 0x295F,
	UPWARDS_HARPOON_WITH_BARB_LEFT_FROM_BAR      = 0x2960,
	DOWNWARDS_HARPOON_WITH_BARB_LEFT_FROM_BAR    = 0x2961,
	LEFTWARDS_HARPOON_WITH_BARB_UP_ABOVE_LEFTWARDS_HARPOON_WITH_BARB_DOWN
	                                             = 0x2962,
	UPWARDS_HARPOON_WITH_BARB_LEFT_BESIDE_UPWARDS_HARPOON_WITH_BARB_RIGHT
	                                             = 0x2963,
	RIGHTWARDS_HARPOON_WITH_BARB_UP_ABOVE_RIGHTWARDS_HARPOON_WITH_BARB_DOWN
	                                             = 0x2964,
	DOWNWARDS_HARPOON_WITH_BARB_LEFT_BESIDE_DOWNWARDS_HARPOON_WITH_BARB_RIGHT
	                                             = 0x2965,
	LEFTWARDS_HARPOON_WITH_BARB_UP_ABOVE_RIGHTWARDS_HARPOON_WITH_BARB_UP
	                                             = 0x2966,
	LEFTWARDS_HARPOON_WITH_BARB_DOWN_ABOVE_RIGHTWARDS_HARPOON_WITH_BARB_DOWN
	                                             = 0x2967,
	RIGHTWARDS_HARPOON_WITH_BARB_UP_ABOVE_LEFTWARDS_HARPOON_WITH_BARB_UP
	                                             = 0x2968,
	RIGHTWARDS_HARPOON_WITH_BARB_DOWN_ABOVE_LEFTWARDS_HARPOON_WITH_BARB_DOWN
	                                             = 0x2969,
	LEFTWARDS_HARPOON_WITH_BARB_UP_ABOVE_LONG_DASH
	                                             = 0x296A,
	LEFTWARDS_HARPOON_WITH_BARB_DOWN_BELOW_LONG_DASH
	                                             = 0x296B,
	RIGHTWARDS_HARPOON_WITH_BARB_UP_ABOVE_LONG_DASH
	                                             = 0x296C,
	RIGHTWARDS_HARPOON_WITH_BARB_DOWN_BELOW_LONG_DASH
	                                             = 0x296D,
	UPWARDS_HARPOON_WITH_BARB_LEFT_BESIDE_DOWNWARDS_HARPOON_WITH_BARB_RIGHT
	                                             = 0x296E,
	DOWNWARDS_HARPOON_WITH_BARB_LEFT_BESIDE_UPWARDS_HARPOON_WITH_BARB_RIGHT
	                                             = 0x296F,
	RIGHT_DOUBLE_ARROW_WITH_ROUNDED_HEAD         = 0x2970,
	EQUALS_SIGN_ABOVE_RIGHTWARDS_ARROW           = 0x2971,
	TILDE_OPERATOR_ABOVE_RIGHTWARDS_ARROW        = 0x2972,
	LEFTWARDS_ARROW_ABOVE_TILDE_OPERATOR         = 0x2973,
	RIGHTWARDS_ARROW_ABOVE_TILDE_OPERATOR        = 0x2974,
	RIGHTWARDS_ARROW_ABOVE_ALMOST_EQUAL_TO       = 0x2975,
	LESS_THAN_ABOVE_LEFTWARDS_ARROW              = 0x2976,
	LEFTWARDS_ARROW_THROUGH_LESS_THAN            = 0x2977,
	GREATER_THAN_ABOVE_RIGHTWARDS_ARROW          = 0x2978,
	SUBSET_ABOVE_RIGHTWARDS_ARROW                = 0x2979,
	LEFTWARDS_ARROW_THROUGH_SUBSET               = 0x297A,
	SUPERSET_ABOVE_LEFTWARDS_ARROW               = 0x297B,
	LEFT_FISH_TAIL                               = 0x297C,
	RIGHT_FISH_TAIL                              = 0x297D,
	UP_FISH_TAIL                                 = 0x297E,
	DOWN_FISH_TAIL                               = 0x297F,

	// Miscellaneous Mathematical Symbols-B 2980-29FF
	TRIPLE_VERTICAL_BAR_DELIMITER                = 0x2980,
	Z_NOTATION_SPOT                              = 0x2981,
	Z_NOTATION_TYPE_COLON                        = 0x2982,
	LEFT_WHITE_CURLY_BRACKET                     = 0x2983,
	RIGHT_WHITE_CURLY_BRACKET                    = 0x2984,
	LEFT_WHITE_PARENTHESIS                       = 0x2985,
	RIGHT_WHITE_PARENTHESIS                      = 0x2986,
	Z_NOTATION_LEFT_IMAGE_BRACKET                = 0x2987,
	Z_NOTATION_RIGHT_IMAGE_BRACKET               = 0x2988,
	Z_NOTATION_LEFT_BINDING_BRACKET              = 0x2989,
	Z_NOTATION_RIGHT_BINDING_BRACKET             = 0x298A,
	LEFT_SQUARE_BRACKET_WITH_UNDERBAR            = 0x298B,
	RIGHT_SQUARE_BRACKET_WITH_UNDERBAR           = 0x298C,
	LEFT_SQUARE_BRACKET_WITH_TICK_IN_TOP_CORNER  = 0x298D,
	RIGHT_SQUARE_BRACKET_WITH_TICK_IN_BOTTOM_CORNER
	                                             = 0x298E,
	LEFT_SQUARE_BRACKET_WITH_TICK_IN_BOTTOM_CORNER
	                                             = 0x298F,
	RIGHT_SQUARE_BRACKET_WITH_TICK_IN_TOP_CORNER = 0x2990,
	LEFT_ANGLE_BRACKET_WITH_DOT                  = 0x2991,
	RIGHT_ANGLE_BRACKET_WITH_DOT                 = 0x2992,
	LEFT_ARC_LESS_THAN_BRACKET                   = 0x2993,
	RIGHT_ARC_GREATER_THAN_BRACKET               = 0x2994,
	DOUBLE_LEFT_ARC_GREATER_THAN_BRACKET         = 0x2995,
	DOUBLE_RIGHT_ARC_LESS_THAN_BRACKET           = 0x2996,
	LEFT_BLACK_TORTOISE_SHELL_BRACKET            = 0x2997,
	RIGHT_BLACK_TORTOISE_SHELL_BRACKET           = 0x2998,
	DOTTED_FENCE                                 = 0x2999,
	VERTICAL_ZIGZAG_LINE                         = 0x299A,
	MEASURED_ANGLE_OPENING_LEFT                  = 0x299B,
	RIGHT_ANGLE_VARIANT_WITH_SQUARE              = 0x299C,
	MEASURED_RIGHT_ANGLE_WITH_DOT                = 0x299D,
	ANGLE_WITH_S_INSIDE                          = 0x299E,
	ACUTE_ANGLE                                  = 0x299F,
	SPHERICAL_ANGLE_OPENING_LEFT                 = 0x29A0,
	SPHERICAL_ANGLE_OPENING_UP                   = 0x29A1,
	TURNED_ANGLE                                 = 0x29A2,
	REVERSED_ANGLE                               = 0x29A3,
	ANGLE_WITH_UNDERBAR                          = 0x29A4,
	REVERSED_ANGLE_WITH_UNDERBAR                 = 0x29A5,
	OBLIQUE_ANGLE_OPENING_UP                     = 0x29A6,
	OBLIQUE_ANGLE_OPENING_DOWN                   = 0x29A7,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_UP_AND_RIGHT
	                                             = 0x29A8,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_UP_AND_LEFT
	                                             = 0x29A9,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_DOWN_AND_RIGHT
	                                             = 0x29AA,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_DOWN_AND_LEFT
	                                             = 0x29AB,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_RIGHT_AND_UP
	                                             = 0x29AC,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_LEFT_AND_UP
	                                             = 0x29AD,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_RIGHT_AND_DOWN
	                                             = 0x29AE,
	MEASURED_ANGLE_WITH_OPEN_ARM_ENDING_IN_ARROW_POINTING_LEFT_AND_DOWN
	                                             = 0x29AF,
	REVERSED_EMPTY_SET                           = 0x29B0,
	EMPTY_SET_WITH_OVERBAR                       = 0x29B1,
	EMPTY_SET_WITH_SMALL_CIRCLE_ABOVE            = 0x29B2,
	EMPTY_SET_WITH_RIGHT_ARROW_ABOVE             = 0x29B3,
	EMPTY_SET_WITH_LEFT_ARROW_ABOVE              = 0x29B4,
	CIRCLE_WITH_HORIZONTAL_BAR                   = 0x29B5,
	CIRCLED_VERTICAL_BAR                         = 0x29B6,
	CIRCLED_PARALLEL                             = 0x29B7,
	CIRCLED_REVERSE_SOLIDUS                      = 0x29B8,
	CIRCLED_PERPENDICULAR                        = 0x29B9,
	CIRCLE_DIVIDED_BY_HORIZONTAL_BAR_AND_TOP_HALF_DIVIDED_BY_VERTICAL_BAR
	                                             = 0x29BA,
	CIRCLE_WITH_SUPERIMPOSED_X                   = 0x29BB,
	CIRCLED_ANTICLOCKWISE_ROTATED_DIVISION_SIGN  = 0x29BC,
	UP_ARROW_THROUGH_CIRCLE                      = 0x29BD,
	CIRCLED_WHITE_BULLET                         = 0x29BE,
	CIRCLED_BULLET                               = 0x29BF,
	CIRCLED_LESS_THAN                            = 0x29C0,
	CIRCLED_GREATER_THAN                         = 0x29C1,
	CIRCLE_WITH_SMALL_CIRCLE_TO_THE_RIGHT        = 0x29C2,
	CIRCLE_WITH_TWO_HORIZONTAL_STROKES_TO_THE_RIGHT
	                                             = 0x29C3,
	SQUARED_RISING_DIAGONAL_SLASH                = 0x29C4,
	SQUARED_FALLING_DIAGONAL_SLASH               = 0x29C5,
	SQUARED_ASTERISK                             = 0x29C6,
	SQUARED_SMALL_CIRCLE                         = 0x29C7,
	SQUARED_SQUARE                               = 0x29C8,
	TWO_JOINED_SQUARES                           = 0x29C9,
	TRIANGLE_WITH_DOT_ABOVE                      = 0x29CA,
	TRIANGLE_WITH_UNDERBAR                       = 0x29CB,
	S_IN_TRIANGLE                                = 0x29CC,
	TRIANGLE_WITH_SERIFS_AT_BOTTOM               = 0x29CD,
	RIGHT_TRIANGLE_ABOVE_LEFT_TRIANGLE           = 0x29CE,
	LEFT_TRIANGLE_BESIDE_VERTICAL_BAR            = 0x29CF,
	VERTICAL_BAR_BESIDE_RIGHT_TRIANGLE           = 0x29D0,
	BOWTIE_WITH_LEFT_HALF_BLACK                  = 0x29D1,
	BOWTIE_WITH_RIGHT_HALF_BLACK                 = 0x29D2,
	BLACK_BOWTIE                                 = 0x29D3,
	TIMES_WITH_LEFT_HALF_BLACK                   = 0x29D4,
	TIMES_WITH_RIGHT_HALF_BLACK                  = 0x29D5,
	WHITE_HOURGLASS                              = 0x29D6,
	BLACK_HOURGLASS                              = 0x29D7,
	LEFT_WIGGLY_FENCE                            = 0x29D8,
	RIGHT_WIGGLY_FENCE                           = 0x29D9,
	LEFT_DOUBLE_WIGGLY_FENCE                     = 0x29DA,
	RIGHT_DOUBLE_WIGGLY_FENCE                    = 0x29DB,
	INCOMPLETE_INFINITY                          = 0x29DC,
	TIE_OVER_INFINITY                            = 0x29DD,
	INFINITY_NEGATED_WITH_VERTICAL_BAR           = 0x29DE,
	DOUBLE_ENDED_MULTIMAP                        = 0x29DF,
	SQUARE_WITH_CONTOURED_OUTLINE                = 0x29E0,
	INCREASES_AS                                 = 0x29E1,
	SHUFFLE_PRODUCT                              = 0x29E2,
	EQUALS_SIGN_AND_SLANTED_PARALLEL             = 0x29E3,
	EQUALS_SIGN_AND_SLANTED_PARALLEL_WITH_TILDE_ABOVE
	                                             = 0x29E4,
	IDENTICAL_TO_AND_SLANTED_PARALLEL            = 0x29E5,
	GLEICH_STARK                                 = 0x29E6,
	THERMODYNAMIC                                = 0x29E7,
	DOWN_POINTING_TRIANGLE_WITH_LEFT_HALF_BLACK  = 0x29E8,
	DOWN_POINTING_TRIANGLE_WITH_RIGHT_HALF_BLACK = 0x29E9,
	BLACK_DIAMOND_WITH_DOWN_ARROW                = 0x29EA,
	BLACK_LOZENGE                                = 0x29EB,
	WHITE_CIRCLE_WITH_DOWN_ARROW                 = 0x29EC,
	BLACK_CIRCLE_WITH_DOWN_ARROW                 = 0x29ED,
	ERROR_BARRED_WHITE_SQUARE                    = 0x29EE,
	ERROR_BARRED_BLACK_SQUARE                    = 0x29EF,
	ERROR_BARRED_WHITE_DIAMOND                   = 0x29F0,
	ERROR_BARRED_BLACK_DIAMOND                   = 0x29F1,
	ERROR_BARRED_WHITE_CIRCLE                    = 0x29F2,
	ERROR_BARRED_BLACK_CIRCLE                    = 0x29F3,
	RULE_DELAYED                                 = 0x29F4,
	REVERSE_SOLIDUS_OPERATOR                     = 0x29F5,
	SOLIDUS_WITH_OVERBAR                         = 0x29F6,
	REVERSE_SOLIDUS_WITH_HORIZONTAL_STROKE       = 0x29F7,
	BIG_SOLIDUS                                  = 0x29F8,
	BIG_REVERSE_SOLIDUS                          = 0x29F9,
	DOUBLE_PLUS                                  = 0x29FA,
	TRIPLE_PLUS                                  = 0x29FB,
	LEFT_POINTING_CURVED_ANGLE_BRACKET           = 0x29FC,
	RIGHT_POINTING_CURVED_ANGLE_BRACKET          = 0x29FD,
	TINY                                         = 0x29FE,
	MINY                                         = 0x29FF,

	// Supplemental Mathematical Operators 2A00-2AFF
	N_ARY_CIRCLED_DOT_OPERATOR                   = 0x2A00,
	N_ARY_CIRCLED_PLUS_OPERATOR                  = 0x2A01,
	N_ARY_CIRCLED_TIMES_OPERATOR                 = 0x2A02,
	N_ARY_UNION_OPERATOR_WITH_DOT                = 0x2A03,
	N_ARY_UNION_OPERATOR_WITH_PLUS               = 0x2A04,
	N_ARY_SQUARE_INTERSECTION_OPERATOR           = 0x2A05,
	N_ARY_SQUARE_UNION_OPERATOR                  = 0x2A06,
	TWO_LOGICAL_AND_OPERATOR                     = 0x2A07,
	TWO_LOGICAL_OR_OPERATOR                      = 0x2A08,
	N_ARY_TIMES_OPERATOR                         = 0x2A09,
	MODULO_TWO_SUM                               = 0x2A0A,
	SUMMATION_WITH_INTEGRAL                      = 0x2A0B,
	QUADRUPLE_INTEGRAL_OPERATOR                  = 0x2A0C,
	FINITE_PART_INTEGRAL                         = 0x2A0D,
	INTEGRAL_WITH_DOUBLE_STROKE                  = 0x2A0E,
	INTEGRAL_AVERAGE_WITH_SLASH                  = 0x2A0F,
	CIRCULATION_FUNCTION                         = 0x2A10,
	ANTICLOCKWISE_INTEGRATION                    = 0x2A11,
	LINE_INTEGRATION_WITH_RECTANGULAR_PATH_AROUND_POLE
	                                             = 0x2A12,
	LINE_INTEGRATION_WITH_SEMICIRCULAR_PATH_AROUND_POLE
	                                             = 0x2A13,
	LINE_INTEGRATION_NOT_INCLUDING_THE_POLE      = 0x2A14,
	INTEGRAL_AROUND_A_POINT_OPERATOR             = 0x2A15,
	QUATERNION_INTEGRAL_OPERATOR                 = 0x2A16,
	INTEGRAL_WITH_LEFTWARDS_ARROW_WITH_HOOK      = 0x2A17,
	INTEGRAL_WITH_TIMES_SIGN                     = 0x2A18,
	INTEGRAL_WITH_INTERSECTION                   = 0x2A19,
	INTEGRAL_WITH_UNION                          = 0x2A1A,
	INTEGRAL_WITH_OVERBAR                        = 0x2A1B,
	INTEGRAL_WITH_UNDERBAR                       = 0x2A1C,
	JOIN                                         = 0x2A1D,
	LARGE_LEFT_TRIANGLE_OPERATOR                 = 0x2A1E,
	Z_NOTATION_SCHEMA_COMPOSITION                = 0x2A1F,
	Z_NOTATION_SCHEMA_PIPING                     = 0x2A20,
	Z_NOTATION_SCHEMA_PROJECTION                 = 0x2A21,
	PLUS_SIGN_WITH_SMALL_CIRCLE_ABOVE            = 0x2A22,
	PLUS_SIGN_WITH_CIRCUMFLEX_ACCENT_ABOVE       = 0x2A23,
	PLUS_SIGN_WITH_TILDE_ABOVE                   = 0x2A24,
	PLUS_SIGN_WITH_DOT_BELOW                     = 0x2A25,
	PLUS_SIGN_WITH_TILDE_BELOW                   = 0x2A26,
	PLUS_SIGN_WITH_SUBSCRIPT_TWO                 = 0x2A27,
	PLUS_SIGN_WITH_BLACK_TRIANGLE                = 0x2A28,
	MINUS_SIGN_WITH_COMMA_ABOVE                  = 0x2A29,
	MINUS_SIGN_WITH_DOT_BELOW                    = 0x2A2A,
	MINUS_SIGN_WITH_FALLING_DOTS                 = 0x2A2B,
	MINUS_SIGN_WITH_RISING_DOTS                  = 0x2A2C,
	PLUS_SIGN_IN_LEFT_HALF_CIRCLE                = 0x2A2D,
	PLUS_SIGN_IN_RIGHT_HALF_CIRCLE               = 0x2A2E,
	VECTOR_OR_CROSS_PRODUCT                      = 0x2A2F,
	MULTIPLICATION_SIGN_WITH_DOT_ABOVE           = 0x2A30,
	MULTIPLICATION_SIGN_WITH_UNDERBAR            = 0x2A31,
	SEMIDIRECT_PRODUCT_WITH_BOTTOM_CLOSED        = 0x2A32,
	SMASH_PRODUCT                                = 0x2A33,
	MULTIPLICATION_SIGN_IN_LEFT_HALF_CIRCLE      = 0x2A34,
	MULTIPLICATION_SIGN_IN_RIGHT_HALF_CIRCLE     = 0x2A35,
	CIRCLED_MULTIPLICATION_SIGN_WITH_CIRCUMFLEX_ACCENT
	                                             = 0x2A36,
	MULTIPLICATION_SIGN_IN_DOUBLE_CIRCLE         = 0x2A37,
	CIRCLED_DIVISION_SIGN                        = 0x2A38,
	PLUS_SIGN_IN_TRIANGLE                        = 0x2A39,
	MINUS_SIGN_IN_TRIANGLE                       = 0x2A3A,
	MULTIPLICATION_SIGN_IN_TRIANGLE              = 0x2A3B,
	INTERIOR_PRODUCT                             = 0x2A3C,
	RIGHTHAND_INTERIOR_PRODUCT                   = 0x2A3D,
	Z_NOTATION_RELATIONAL_COMPOSITION            = 0x2A3E,
	AMALGAMATION_OR_COPRODUCT                    = 0x2A3F,
	INTERSECTION_WITH_DOT                        = 0x2A40,
	UNION_WITH_MINUS_SIGN                        = 0x2A41,
	UNION_WITH_OVERBAR                           = 0x2A42,
	INTERSECTION_WITH_OVERBAR                    = 0x2A43,
	INTERSECTION_WITH_LOGICAL_AND                = 0x2A44,
	UNION_WITH_LOGICAL_OR                        = 0x2A45,
	UNION_ABOVE_INTERSECTION                     = 0x2A46,
	INTERSECTION_ABOVE_UNION                     = 0x2A47,
	UNION_ABOVE_BAR_ABOVE_INTERSECTION           = 0x2A48,
	INTERSECTION_ABOVE_BAR_ABOVE_UNION           = 0x2A49,
	UNION_BESIDE_AND_JOINED_WITH_UNION           = 0x2A4A,
	INTERSECTION_BESIDE_AND_JOINED_WITH_INTERSECTION
	                                             = 0x2A4B,
	CLOSED_UNION_WITH_SERIFS                     = 0x2A4C,
	CLOSED_INTERSECTION_WITH_SERIFS              = 0x2A4D,
	DOUBLE_SQUARE_INTERSECTION                   = 0x2A4E,
	DOUBLE_SQUARE_UNION                          = 0x2A4F,
	CLOSED_UNION_WITH_SERIFS_AND_SMASH_PRODUCT   = 0x2A50,
	LOGICAL_AND_WITH_DOT_ABOVE                   = 0x2A51,
	LOGICAL_OR_WITH_DOT_ABOVE                    = 0x2A52,
	DOUBLE_LOGICAL_AND                           = 0x2A53,
	DOUBLE_LOGICAL_OR                            = 0x2A54,
	TWO_INTERSECTING_LOGICAL_AND                 = 0x2A55,
	TWO_INTERSECTING_LOGICAL_OR                  = 0x2A56,
	SLOPING_LARGE_OR                             = 0x2A57,
	SLOPING_LARGE_AND                            = 0x2A58,
	LOGICAL_OR_OVERLAPPING_LOGICAL_AND           = 0x2A59,
	LOGICAL_AND_WITH_MIDDLE_STEM                 = 0x2A5A,
	LOGICAL_OR_WITH_MIDDLE_STEM                  = 0x2A5B,
	LOGICAL_AND_WITH_HORIZONTAL_DASH             = 0x2A5C,
	LOGICAL_OR_WITH_HORIZONTAL_DASH              = 0x2A5D,
	LOGICAL_AND_WITH_DOUBLE_OVERBAR              = 0x2A5E,
	LOGICAL_AND_WITH_UNDERBAR                    = 0x2A5F,
	LOGICAL_AND_WITH_DOUBLE_UNDERBAR             = 0x2A60,
	SMALL_VEE_WITH_UNDERBAR                      = 0x2A61,
	LOGICAL_OR_WITH_DOUBLE_OVERBAR               = 0x2A62,
	LOGICAL_OR_WITH_DOUBLE_UNDERBAR              = 0x2A63,
	Z_NOTATION_DOMAIN_ANTIRESTRICTION            = 0x2A64,
	Z_NOTATION_RANGE_ANTIRESTRICTION             = 0x2A65,
	EQUALS_SIGN_WITH_DOT_BELOW                   = 0x2A66,
	IDENTICAL_WITH_DOT_ABOVE                     = 0x2A67,
	TRIPLE_HORIZONTAL_BAR_WITH_DOUBLE_VERTICAL_STROKE
	                                             = 0x2A68,
	TRIPLE_HORIZONTAL_BAR_WITH_TRIPLE_VERTICAL_STROKE
	                                             = 0x2A69,
	TILDE_OPERATOR_WITH_DOT_ABOVE                = 0x2A6A,
	TILDE_OPERATOR_WITH_RISING_DOTS              = 0x2A6B,
	SIMILAR_MINUS_SIMILAR                        = 0x2A6C,
	CONGRUENT_WITH_DOT_ABOVE                     = 0x2A6D,
	EQUALS_WITH_ASTERISK                         = 0x2A6E,
	ALMOST_EQUAL_TO_WITH_CIRCUMFLEX_ACCENT       = 0x2A6F,
	APPROXIMATELY_EQUAL_OR_EQUAL_TO              = 0x2A70,
	EQUALS_SIGN_ABOVE_PLUS_SIGN                  = 0x2A71,
	PLUS_SIGN_ABOVE_EQUALS_SIGN                  = 0x2A72,
	EQUALS_SIGN_ABOVE_TILDE_OPERATOR             = 0x2A73,
	DOUBLE_COLON_EQUAL                           = 0x2A74,
	TWO_CONSECUTIVE_EQUALS_SIGNS                 = 0x2A75,
	THREE_CONSECUTIVE_EQUALS_SIGNS               = 0x2A76,
	EQUALS_SIGN_WITH_TWO_DOTS_ABOVE_AND_TWO_DOTS_BELOW
	                                             = 0x2A77,
	EQUIVALENT_WITH_FOUR_DOTS_ABOVE              = 0x2A78,
	LESS_THAN_WITH_CIRCLE_INSIDE                 = 0x2A79,
	GREATER_THAN_WITH_CIRCLE_INSIDE              = 0x2A7A,
	LESS_THAN_WITH_QUESTION_MARK_ABOVE           = 0x2A7B,
	GREATER_THAN_WITH_QUESTION_MARK_ABOVE        = 0x2A7C,
	LESS_THAN_OR_SLANTED_EQUAL_TO                = 0x2A7D,
	GREATER_THAN_OR_SLANTED_EQUAL_TO             = 0x2A7E,
	LESS_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_INSIDE
	                                             = 0x2A7F,
	GREATER_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_INSIDE
	                                             = 0x2A80,
	LESS_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_ABOVE = 0x2A81,
	GREATER_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_ABOVE
	                                             = 0x2A82,
	LESS_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_ABOVE_RIGHT
	                                             = 0x2A83,
	GREATER_THAN_OR_SLANTED_EQUAL_TO_WITH_DOT_ABOVE_LEFT
	                                             = 0x2A84,
	LESS_THAN_OR_APPROXIMATE                     = 0x2A85,
	GREATER_THAN_OR_APPROXIMATE                  = 0x2A86,
	LESS_THAN_AND_SINGLE_LINE_NOT_EQUAL_TO       = 0x2A87,
	GREATER_THAN_AND_SINGLE_LINE_NOT_EQUAL_TO    = 0x2A88,
	LESS_THAN_AND_NOT_APPROXIMATE                = 0x2A89,
	GREATER_THAN_AND_NOT_APPROXIMATE             = 0x2A8A,
	LESS_THAN_ABOVE_DOUBLE_LINE_EQUAL_ABOVE_GREATER_THAN
	                                             = 0x2A8B,
	GREATER_THAN_ABOVE_DOUBLE_LINE_EQUAL_ABOVE_LESS_THAN
	                                             = 0x2A8C,
	LESS_THAN_ABOVE_SIMILAR_OR_EQUAL             = 0x2A8D,
	GREATER_THAN_ABOVE_SIMILAR_OR_EQUAL          = 0x2A8E,
	LESS_THAN_ABOVE_SIMILAR_ABOVE_GREATER_THAN   = 0x2A8F,
	GREATER_THAN_ABOVE_SIMILAR_ABOVE_LESS_THAN   = 0x2A90,
	LESS_THAN_ABOVE_GREATER_THAN_ABOVE_DOUBLE_LINE_EQUAL
	                                             = 0x2A91,
	GREATER_THAN_ABOVE_LESS_THAN_ABOVE_DOUBLE_LINE_EQUAL
	                                             = 0x2A92,
	LESS_THAN_ABOVE_SLANTED_EQUAL_ABOVE_GREATER_THAN_ABOVE_SLANTED_EQUAL
	                                             = 0x2A93,
	GREATER_THAN_ABOVE_SLANTED_EQUAL_ABOVE_LESS_THAN_ABOVE_SLANTED_EQUAL
	                                             = 0x2A94,
	SLANTED_EQUAL_TO_OR_LESS_THAN                = 0x2A95,
	SLANTED_EQUAL_TO_OR_GREATER_THAN             = 0x2A96,
	SLANTED_EQUAL_TO_OR_LESS_THAN_WITH_DOT_INSIDE
	                                             = 0x2A97,
	SLANTED_EQUAL_TO_OR_GREATER_THAN_WITH_DOT_INSIDE
	                                             = 0x2A98,
	DOUBLE_LINE_EQUAL_TO_OR_LESS_THAN            = 0x2A99,
	DOUBLE_LINE_EQUAL_TO_OR_GREATER_THAN         = 0x2A9A,
	DOUBLE_LINE_SLANTED_EQUAL_TO_OR_LESS_THAN    = 0x2A9B,
	DOUBLE_LINE_SLANTED_EQUAL_TO_OR_GREATER_THAN = 0x2A9C,
	SIMILAR_OR_LESS_THAN                         = 0x2A9D,
	SIMILAR_OR_GREATER_THAN                      = 0x2A9E,
	SIMILAR_ABOVE_LESS_THAN_ABOVE_EQUALS_SIGN    = 0x2A9F,
	SIMILAR_ABOVE_GREATER_THAN_ABOVE_EQUALS_SIGN = 0x2AA0,
	DOUBLE_NESTED_LESS_THAN                      = 0x2AA1,
	DOUBLE_NESTED_GREATER_THAN                   = 0x2AA2,
	DOUBLE_NESTED_LESS_THAN_WITH_UNDERBAR        = 0x2AA3,
	GREATER_THAN_OVERLAPPING_LESS_THAN           = 0x2AA4,
	GREATER_THAN_BESIDE_LESS_THAN                = 0x2AA5,
	LESS_THAN_CLOSED_BY_CURVE                    = 0x2AA6,
	GREATER_THAN_CLOSED_BY_CURVE                 = 0x2AA7,
	LESS_THAN_CLOSED_BY_CURVE_ABOVE_SLANTED_EQUAL
	                                             = 0x2AA8,
	GREATER_THAN_CLOSED_BY_CURVE_ABOVE_SLANTED_EQUAL
	                                             = 0x2AA9,
	SMALLER_THAN                                 = 0x2AAA,
	LARGER_THAN                                  = 0x2AAB,
	SMALLER_THAN_OR_EQUAL_TO                     = 0x2AAC,
	LARGER_THAN_OR_EQUAL_TO                      = 0x2AAD,
	EQUALS_SIGN_WITH_BUMPY_ABOVE                 = 0x2AAE,
	PRECEDES_ABOVE_SINGLE_LINE_EQUALS_SIGN       = 0x2AAF,
	SUCCEEDS_ABOVE_SINGLE_LINE_EQUALS_SIGN       = 0x2AB0,
	PRECEDES_ABOVE_SINGLE_LINE_NOT_EQUAL_TO      = 0x2AB1,
	SUCCEEDS_ABOVE_SINGLE_LINE_NOT_EQUAL_TO      = 0x2AB2,
	PRECEDES_ABOVE_EQUALS_SIGN                   = 0x2AB3,
	SUCCEEDS_ABOVE_EQUALS_SIGN                   = 0x2AB4,
	PRECEDES_ABOVE_NOT_EQUAL_TO                  = 0x2AB5,
	SUCCEEDS_ABOVE_NOT_EQUAL_TO                  = 0x2AB6,
	PRECEDES_ABOVE_ALMOST_EQUAL_TO               = 0x2AB7,
	SUCCEEDS_ABOVE_ALMOST_EQUAL_TO               = 0x2AB8,
	PRECEDES_ABOVE_NOT_ALMOST_EQUAL_TO           = 0x2AB9,
	SUCCEEDS_ABOVE_NOT_ALMOST_EQUAL_TO           = 0x2ABA,
	DOUBLE_PRECEDES                              = 0x2ABB,
	DOUBLE_SUCCEEDS                              = 0x2ABC,
	SUBSET_WITH_DOT                              = 0x2ABD,
	SUPERSET_WITH_DOT                            = 0x2ABE,
	SUBSET_WITH_PLUS_SIGN_BELOW                  = 0x2ABF,
	SUPERSET_WITH_PLUS_SIGN_BELOW                = 0x2AC0,
	SUBSET_WITH_MULTIPLICATION_SIGN_BELOW        = 0x2AC1,
	SUPERSET_WITH_MULTIPLICATION_SIGN_BELOW      = 0x2AC2,
	SUBSET_OF_OR_EQUAL_TO_WITH_DOT_ABOVE         = 0x2AC3,
	SUPERSET_OF_OR_EQUAL_TO_WITH_DOT_ABOVE       = 0x2AC4,
	SUBSET_OF_ABOVE_EQUALS_SIGN                  = 0x2AC5,
	SUPERSET_OF_ABOVE_EQUALS_SIGN                = 0x2AC6,
	SUBSET_OF_ABOVE_TILDE_OPERATOR               = 0x2AC7,
	SUPERSET_OF_ABOVE_TILDE_OPERATOR             = 0x2AC8,
	SUBSET_OF_ABOVE_ALMOST_EQUAL_TO              = 0x2AC9,
	SUPERSET_OF_ABOVE_ALMOST_EQUAL_TO            = 0x2ACA,
	SUBSET_OF_ABOVE_NOT_EQUAL_TO                 = 0x2ACB,
	SUPERSET_OF_ABOVE_NOT_EQUAL_TO               = 0x2ACC,
	SQUARE_LEFT_OPEN_BOX_OPERATOR                = 0x2ACD,
	SQUARE_RIGHT_OPEN_BOX_OPERATOR               = 0x2ACE,
	CLOSED_SUBSET                                = 0x2ACF,
	CLOSED_SUPERSET                              = 0x2AD0,
	CLOSED_SUBSET_OR_EQUAL_TO                    = 0x2AD1,
	CLOSED_SUPERSET_OR_EQUAL_TO                  = 0x2AD2,
	SUBSET_ABOVE_SUPERSET                        = 0x2AD3,
	SUPERSET_ABOVE_SUBSET                        = 0x2AD4,
	SUBSET_ABOVE_SUBSET                          = 0x2AD5,
	SUPERSET_ABOVE_SUPERSET                      = 0x2AD6,
	SUPERSET_BESIDE_SUBSET                       = 0x2AD7,
	SUPERSET_BESIDE_AND_JOINED_BY_DASH_WITH_SUBSET
	                                             = 0x2AD8,
	ELEMENT_OF_OPENING_DOWNWARDS                 = 0x2AD9,
	PITCHFORK_WITH_TEE_TOP                       = 0x2ADA,
	TRANSVERSAL_INTERSECTION                     = 0x2ADB,
	FORKING                                      = 0x2ADC,
	NONFORKING                                   = 0x2ADD,
	SHORT_LEFT_TACK                              = 0x2ADE,
	SHORT_DOWN_TACK                              = 0x2ADF,
	SHORT_UP_TACK                                = 0x2AE0,
	PERPENDICULAR_WITH_S                         = 0x2AE1,
	VERTICAL_BAR_TRIPLE_RIGHT_TURNSTILE          = 0x2AE2,
	DOUBLE_VERTICAL_BAR_LEFT_TURNSTILE           = 0x2AE3,
	VERTICAL_BAR_DOUBLE_LEFT_TURNSTILE           = 0x2AE4,
	DOUBLE_VERTICAL_BAR_DOUBLE_LEFT_TURNSTILE    = 0x2AE5,
	LONG_DASH_FROM_LEFT_MEMBER_OF_DOUBLE_VERTICAL
	                                             = 0x2AE6,
	SHORT_DOWN_TACK_WITH_OVERBAR                 = 0x2AE7,
	SHORT_UP_TACK_WITH_UNDERBAR                  = 0x2AE8,
	SHORT_UP_TACK_ABOVE_SHORT_DOWN_TACK          = 0x2AE9,
	DOUBLE_DOWN_TACK                             = 0x2AEA,
	DOUBLE_UP_TACK                               = 0x2AEB,
	DOUBLE_STROKE_NOT_SIGN                       = 0x2AEC,
	REVERSED_DOUBLE_STROKE_NOT_SIGN              = 0x2AED,
	DOES_NOT_DIVIDE_WITH_REVERSED_NEGATION_SLASH = 0x2AEE,
	VERTICAL_LINE_WITH_CIRCLE_ABOVE              = 0x2AEF,
	VERTICAL_LINE_WITH_CIRCLE_BELOW              = 0x2AF0,
	DOWN_TACK_WITH_CIRCLE_BELOW                  = 0x2AF1,
	PARALLEL_WITH_HORIZONTAL_STROKE              = 0x2AF2,
	PARALLEL_WITH_TILDE_OPERATOR                 = 0x2AF3,
	TRIPLE_VERTICAL_BAR_BINARY_RELATION          = 0x2AF4,
	TRIPLE_VERTICAL_BAR_WITH_HORIZONTAL_STROKE   = 0x2AF5,
	TRIPLE_COLON_OPERATOR                        = 0x2AF6,
	TRIPLE_NESTED_LESS_THAN                      = 0x2AF7,
	TRIPLE_NESTED_GREATER_THAN                   = 0x2AF8,
	DOUBLE_LINE_SLANTED_LESS_THAN_OR_EQUAL_TO    = 0x2AF9,
	DOUBLE_LINE_SLANTED_GREATER_THAN_OR_EQUAL_TO = 0x2AFA,
	TRIPLE_SOLIDUS_BINARY_RELATION               = 0x2AFB,
	LARGE_TRIPLE_VERTICAL_BAR_OPERATOR           = 0x2AFC,
	DOUBLE_SOLIDUS_OPERATOR                      = 0x2AFD,
	WHITE_VERTICAL_BAR                           = 0x2AFE,
	N_ARY_WHITE_VERTICAL_BAR                     = 0x2AFF;


#ifdef UNICODE_FULLWIDTH
const gunichar  fullwidth                        (const char            c);
Glib::ustring   fullwidth                        (const Glib::ustring&  str);
#endif


// Superscripts and Subscripts
const gunichar  superscript                      (const char            c);
Glib::ustring   superscript                      (const Glib::ustring&  str);
Glib::ustring   superscript_num                  (long                  l);
const gunichar  subscript                        (const char            c);
Glib::ustring   subscript                        (const Glib::ustring&  str);
Glib::ustring   subscript_num                    (long                  l);


// Mathematical Alphanumeric Symbols
const gunichar  mathematical_bold                (const char            c);
const gunichar  mathematical_bold                (const gunichar        uc);
Glib::ustring   mathematical_bold                (const Glib::ustring&  str);
Glib::ustring   mathematical_bold_num            (long                  l);
const gunichar  mathematical_italic              (const char            c);
const gunichar  mathematical_italic              (const gunichar        uc);
Glib::ustring   mathematical_italic              (const Glib::ustring&  str);
const gunichar  mathematical_bold_italic         (const char            c);
const gunichar  mathematical_bold_italic         (const gunichar        uc);
Glib::ustring   mathematical_bold_italic         (const Glib::ustring&  str);
const gunichar  mathematical_script              (const char            c);
Glib::ustring   mathematical_script              (const Glib::ustring&  str);
const gunichar  mathematical_bold_script         (const char            c);
Glib::ustring   mathematical_bold_script         (const Glib::ustring&  str);
const gunichar  mathematical_fraktur             (const char            c);
Glib::ustring   mathematical_fraktur             (const Glib::ustring&  str);
const gunichar  mathematical_double_struck       (const char            c);
Glib::ustring   mathematical_double_struck       (const Glib::ustring&  str);
Glib::ustring   mathematical_double_struck_num   (long                  ul);
const gunichar  mathematical_bold_fraktur        (const char            c);
Glib::ustring   mathematical_bold_fraktur        (const Glib::ustring&  str);
const gunichar  mathematical_sans_serif          (const char            c);
Glib::ustring   mathematical_sans_serif          (const Glib::ustring&  str);
Glib::ustring   mathematical_sans_serif_num      (long                  l);
const gunichar  mathematical_sans_serif_bold     (const char            c);
const gunichar  mathematical_sans_serif_bold     (const gunichar        uc);
Glib::ustring   mathematical_sans_serif_bold     (const Glib::ustring&  str);
Glib::ustring   mathematical_sans_serif_bold_num (long                  l);
const gunichar  mathematical_sans_serif_italic   (const char            c);
Glib::ustring   mathematical_sans_serif_italic   (const Glib::ustring&  str);
const gunichar  mathematical_sans_serif_bold_italic
                                                 (const char            c);
const gunichar  mathematical_sans_serif_bold_italic
                                                 (const gunichar        uc);
Glib::ustring   mathematical_sans_serif_bold_italic
                                                 (const Glib::ustring&  str);
const gunichar  mathematical_monospace           (const char            c);
Glib::ustring   mathematical_monospace           (const Glib::ustring&  str);
Glib::ustring   mathematical_monospace_num       (long                  l);

} /* namespace Unicode */

#endif /* UNICODE_H_ */
